using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

const string protocol = "aura.native-programs.precompiled.v1";
var options = Options.Parse(args);
var sources = new SortedSet<string>(StringComparer.Ordinal);
CollectCampaign(options.CampaignPath, sources);
CollectRuleset(options.RulesetPath, sources);

var programs = sources
    .Select(Normalize)
    .Where(item => !string.IsNullOrWhiteSpace(item))
    .Distinct(StringComparer.Ordinal)
    .Select(item => new ProgramDefinition(Hash(item), item))
    .OrderBy(item => item.Key, StringComparer.Ordinal)
    .ToList();

Directory.CreateDirectory(Path.GetDirectoryName(options.OutputPath) ?? ".");
var sourceChanged = WriteIfChanged(
    options.OutputPath,
    GenerateSource(programs),
    new UTF8Encoding(false));

var manifest = new
{
    schemaVersion = 1,
    runtimeProtocol = protocol,
    programCount = programs.Count,
    campaignSha256 = FileHash(options.CampaignPath),
    rulesetSha256 = FileHash(options.RulesetPath),
    programSetSha256 = Hash(string.Join("\n", programs.Select(item => item.Key)))
};
Directory.CreateDirectory(Path.GetDirectoryName(options.ManifestPath) ?? ".");
var manifestChanged = WriteIfChanged(
    options.ManifestPath,
    JsonSerializer.Serialize(
        manifest,
        new JsonSerializerOptions { WriteIndented = true }),
    new UTF8Encoding(false));

Console.WriteLine(
    $"{(sourceChanged ? "Generated" : "Reused")} {programs.Count} precompiled native programs: {options.OutputPath}"
    + (manifestChanged ? " (manifest updated)" : ""));

static bool WriteIfChanged(
    string path,
    string content,
    Encoding encoding)
{
    content = content
        .Replace("\r\n", "\n", StringComparison.Ordinal)
        .Replace('\r', '\n');
    content = Regex.Replace(content, @"[ \t]+(?=\n|$)", "");
    if (File.Exists(path)
        && string.Equals(
            File.ReadAllText(path, encoding),
            content,
            StringComparison.Ordinal))
    {
        return false;
    }
    File.WriteAllText(path, content, encoding);
    return true;
}

static void CollectCampaign(string path, ISet<string> target)
{
    using var document = JsonDocument.Parse(File.ReadAllText(path));
    if (!document.RootElement.TryGetProperty("rewards", out var rewards))
    {
        return;
    }
    foreach (var reward in rewards.EnumerateArray())
    {
        AddString(reward, "fightScript", target);
    }
}

static void CollectRuleset(string path, ISet<string> target)
{
    using var document = JsonDocument.Parse(File.ReadAllText(path));
    CollectMetadata(
        document.RootElement,
        "cards",
        new[]
        {
            "NativeInitScript",
            "NativeUseScript",
            "NativeDrawScript",
            "NativeDropScript"
        },
        target);
    CollectMetadata(
        document.RootElement,
        "statuses",
        new[]
        {
            "NativeInitScript",
            "NativeApplyScript",
            "NativeClearScript"
        },
        target);
}

static void CollectMetadata(
    JsonElement root,
    string collectionName,
    IReadOnlyList<string> keys,
    ISet<string> target)
{
    if (!root.TryGetProperty(collectionName, out var collection))
    {
        return;
    }
    foreach (var item in collection.EnumerateArray())
    {
        if (!item.TryGetProperty("metadata", out var metadata)
            || metadata.ValueKind != JsonValueKind.Object)
        {
            continue;
        }
        foreach (var key in keys)
        {
            AddString(metadata, key, target);
        }
    }
}

static void AddString(JsonElement owner, string key, ISet<string> target)
{
    if (owner.TryGetProperty(key, out var value)
        && value.ValueKind == JsonValueKind.String)
    {
        var script = value.GetString();
        if (!string.IsNullOrWhiteSpace(script))
        {
            target.Add(script);
        }
    }
}

static string GenerateSource(IReadOnlyList<ProgramDefinition> programs)
{
    var source = new StringBuilder(1024 * 1024);
    source.AppendLine("// <auto-generated />");
    source.AppendLine("#nullable disable");
    source.AppendLine("using System;");
    source.AppendLine("using System.Collections.Generic;");
    source.AppendLine("using System.Linq;");
    source.AppendLine();
    source.AppendLine("namespace AuraToolsExp.Dll.Features.AutoBattle;");
    source.AppendLine();
    source.AppendLine("public sealed partial class NativeRewardScriptGlobals");
    source.AppendLine("{");
    source.AppendLine(
        $"    internal const string PrecompiledProgramProtocol = \"{protocol}\";");
    source.AppendLine(
        $"    internal const int PrecompiledProgramCount = {programs.Count};");
    source.AppendLine();
    source.AppendLine(
        "    internal bool TryRunPrecompiledProgram(string key, out string message)");
    source.AppendLine("    {");
    source.AppendLine("        try");
    source.AppendLine("        {");
    source.AppendLine("            switch (key)");
    source.AppendLine("            {");
    for (var i = 0; i < programs.Count; i++)
    {
        source.AppendLine($"                case \"{programs[i].Key}\":");
        source.AppendLine($"                    NativeProgram_{i:D4}();");
        source.AppendLine("                    message = \"\";");
        source.AppendLine("                    return true;");
    }
    source.AppendLine("                default:");
    source.AppendLine(
        "                    message = \"precompiled native program is missing: \" + key;");
    source.AppendLine("                    return false;");
    source.AppendLine("            }");
    source.AppendLine("        }");
    source.AppendLine("        catch (Exception ex)");
    source.AppendLine("        {");
    source.AppendLine(
        "            message = ex.GetType().Name + \":\" + ex.Message"
        + " + (string.IsNullOrWhiteSpace(ex.StackTrace)"
        + " ? \"\" : \":\" + ex.StackTrace.Replace(Environment.NewLine, \" <- \"));");
    source.AppendLine("            return false;");
    source.AppendLine("        }");
    source.AppendLine("    }");
    source.AppendLine();
    source.AppendLine(
        "    internal static bool ContainsPrecompiledProgram(string key)");
    source.AppendLine("    {");
    source.AppendLine("        switch (key)");
    source.AppendLine("        {");
    foreach (var program in programs)
    {
        source.AppendLine($"            case \"{program.Key}\":");
    }
    source.AppendLine("                return true;");
    source.AppendLine("            default:");
    source.AppendLine("                return false;");
    source.AppendLine("        }");
    source.AppendLine("    }");
    source.AppendLine();
    for (var i = 0; i < programs.Count; i++)
    {
        source.AppendLine($"    private void NativeProgram_{i:D4}()");
        source.AppendLine("    {");
        foreach (var line in programs[i].Source.Replace("\r\n", "\n").Split('\n'))
        {
            source.Append("        ");
            source.AppendLine(line);
        }
        source.AppendLine("    }");
        source.AppendLine();
    }
    source.AppendLine("}");
    return source.ToString();
}

static string Normalize(string script)
{
    var result = script ?? "";
    result = Regex.Replace(
        result,
        @"\bDataId\.([A-Za-z_][A-Za-z0-9_]*)",
        match => "\"" + match.Groups[1].Value + "\"");
    result = result.Replace(
        "EventType.ScriptExecute.ToString()",
        "\"ScriptExecute\"");
    result = Regex.Replace(result, @"\bHurtData\b", "NativeRewardHurtData");
    result = Regex.Replace(result, @"\bActionData\b", "NativeRewardActionData");
    result = Regex.Replace(result, @"\bCreateData\b", "NativeRewardCreateData");
    result = Regex.Replace(result, @"\bBurnData\b", "NativeRewardBurnData");
    result = Regex.Replace(result, @"\bAddBuffData\b", "NativeRewardAddBuffData");
    result = Regex.Replace(result, @"\bOutHealData\b", "NativeRewardOutHealData");
    result = Regex.Replace(
        result,
        @"\bScriptExecuteData\b",
        "NativeRewardScriptExecuteData");
    result = Regex.Replace(result, @"\bIDataConfig\b", "NativeRewardDataConfig");
    result = Regex.Replace(result, @"\bDataConfig\b", "NativeRewardDataConfig");
    result = Regex.Replace(result, @"\bCardItem\b", "NativeRewardCardItem");
    result = Regex.Replace(
        result,
        @"(\b[A-Za-z_][A-Za-z0-9_]*)\.data\.Localize\(([^)\r\n]+)\)",
        "$1.data.GetValueOrDefault($2, \"\")");
    result = result.Replace("FightManager.Instance.statuses", "Statuses");
    result = Regex.Replace(result, @"\bDataType\b", "NativeRewardDataType");
    result = Regex.Replace(result, @"\bIStatusManager\b", "NativeRewardActor");
    result = result.Replace(
        "NativeRewardActor.State",
        "NativeRewardActorState");
    result = result.Replace("Dice.State", "NativeRewardDiceState");
    result = Regex.Replace(
        result,
        @"\bFightCardManager\b",
        "NativeRewardFightCardManager");
    result = Regex.Replace(
        result,
        @"\bRoleTable\b",
        "NativeRewardRoleTable");
    result = result.Replace(
        "new List<NativeRewardDataConfig>(DeckCard)",
        "DeckCard.Select(x => x.dataConfig).ToList()");
    result = result.Replace(
        "new List<NativeRewardDataConfig>(UsedCard)",
        "UsedCard.Select(x => x.dataConfig).ToList()");
    result = Regex.Replace(
        result,
        @"\bnew\s+NativeRewardDataConfig\s*\(",
        "CreateDataConfig(");
    result = Regex.Replace(
        result,
        @"\b(?<config>[A-Za-z_][A-Za-z0-9_]*)\.data\s*=\s*"
        + @"(?<value>[A-Za-z_][A-Za-z0-9_]*)\s*;",
        "${config}.ReplaceData(${value});");
    result = Regex.Replace(
        result,
        @"\b(?<pile>DeckCard|HandCard|UsedCard)\s*"
        + @"\.Cast<NativeRewardDataConfig>\s*\(\s*\)",
        "${pile}.Select(x => x.dataConfig)");
    result = Regex.Replace(
        result,
        @"\b(?<actor>Self|Target)\.AddBuff\(\s*"
        + @"(?<id>""[^""]+"")\s*,\s*(?<amount>[^,)]+)\s*\)"
        + @"\.GetBuff\(\s*\k<id>\s*\)",
        "AddAndGetBuff(${actor}, ${id}, ${amount})");
    result = result.Replace(
        "effectList.Add((dataConfig, () => { RunScript(\"UseScript\"); }));",
        "effectList.Add(dataConfig, () => { RunScript(\"UseScript\"); });");
    result = result.Replace(
        "effectList.Add((tempCard.dataConfig, () => { tempCard.dataConfig.scriptExecutor.RunScript(\"UseScript\"); }));",
        "effectList.Add(tempCard.dataConfig, () => { UseCard(tempCard.dataConfig); });");
    result = Regex.Replace(
        result,
        @"(?<effects>\b[A-Za-z_][A-Za-z0-9_]*\??\.effectList)"
        + @"\.First\s*\(\s*\)\.action\s*\(\s*\)",
        "${effects}.InvokeFirst()");
    result = Regex.Replace(
        result,
        @"(?<effects>\b[A-Za-z_][A-Za-z0-9_]*\??\.effectList)"
        + @"\.Last\s*\(\s*\)\.action\s*\(\s*\)",
        "${effects}.InvokeLast()");
    result = Regex.Replace(
        result,
        @"int\s+c\s*=\s*DeckCard\.Count\s*;\s*"
        + @"for\s*\(\s*int\s+i\s*=\s*c\s*-\s*1\s*;\s*i\s*>=\s*0\s*;\s*i--\s*\)\s*"
        + @"\{\s*var\s+d\s*=\s*DeckCard\s*\[\s*i\s*\]\s*;\s*"
        + @"UseCard\s*\(\s*d\s*\)\s*;\s*"
        + @"BurnCardByData\s*\(\s*d\s*\)\s*;\s*\}\s*"
        + @"if\s*\(\s*c\s*>\s*0\s*\)\s*"
        + @"\{\s*ChangePower\s*\(\s*c\.ToString\s*\(\s*\)\s*\)\s*;\s*\}",
        "UseAndBurnDrawPileSnapshot();");
    result = Regex.Replace(result, @"\bMathf\b", "NativeRewardMathf");
    result = Regex.Replace(result, @"\bDebug\b", "NativeRewardDebug");
    return result;
}

static string Hash(string value)
{
    return Convert.ToHexString(
        SHA256.HashData(Encoding.UTF8.GetBytes(value ?? "")));
}

static string FileHash(string path)
{
    using var stream = File.OpenRead(path);
    return Convert.ToHexString(SHA256.HashData(stream));
}

internal sealed record ProgramDefinition(string Key, string Source);

internal sealed class Options
{
    public string CampaignPath { get; private set; } = "";

    public string RulesetPath { get; private set; } = "";

    public string OutputPath { get; private set; } = "";

    public string ManifestPath { get; private set; } = "";

    public static Options Parse(string[] args)
    {
        var result = new Options();
        for (var i = 0; i < args.Length - 1; i += 2)
        {
            switch (args[i])
            {
                case "--campaign":
                    result.CampaignPath = args[i + 1];
                    break;
                case "--ruleset":
                    result.RulesetPath = args[i + 1];
                    break;
                case "--output":
                    result.OutputPath = args[i + 1];
                    break;
                case "--manifest":
                    result.ManifestPath = args[i + 1];
                    break;
            }
        }
        if (string.IsNullOrWhiteSpace(result.CampaignPath)
            || string.IsNullOrWhiteSpace(result.RulesetPath)
            || string.IsNullOrWhiteSpace(result.OutputPath)
            || string.IsNullOrWhiteSpace(result.ManifestPath))
        {
            throw new ArgumentException(
                "Usage: --campaign <path> --ruleset <path> "
                + "--output <path> --manifest <path>");
        }
        return result;
    }
}
