<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AuraDecisionShared\*.cs" Link="Decision\%(Filename)%(Extension)" />
    <Compile Include="..\AuraCombatAiShared\*.cs" Link="Combat\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
