<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ManagedPath Condition="'$(ManagedPath)' == ''">$(MSBuildProjectDirectory)\..\Managed</ManagedPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Witch.Core">
      <HintPath>$(ManagedPath)\Witch.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MemoryPack.Core">
      <HintPath>$(ManagedPath)\MemoryPack.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
