function SunExp_RegisterDynamicMethod(config, name, fn)
    if config == nil or fn == nil then
        return
    end
    config:AddDynamicMethod(name, fn)
end

function SunExp_RegisterDynamicMethods(config)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerInfo", SunExp_PlayerInfo)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerGetVar", SunExp_PlayerGetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerSetVar", SunExp_PlayerSetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GainGold", SunExp_GainGold)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddCardReward", SunExp_AddCardReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddRelicReward", SunExp_AddRelicReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBlessReward", SunExp_AddBlessReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_EndEvent", SunExp_EndEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_ShowCaption", SunExp_ShowCaption)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaProgressKey", SunExp_WunaProgressKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetWunaProgress", SunExp_GetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetWunaProgress", SunExp_SetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_AdvanceWunaEvent", SunExp_AdvanceWunaEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaFinish", SunExp_WunaFinish)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardCard", SunExp_WunaRewardCard)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardRelic", SunExp_WunaRewardRelic)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardBless", SunExp_WunaRewardBless)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardNone", SunExp_WunaRewardNone)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetNodeData", SunExp_TrySetNodeData)
    SunExp_RegisterDynamicMethod(config, "SunExp_CreateSolarEventNode", SunExp_CreateSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventNode", SunExp_TryAppendSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryInjectSolarEventMapCard", SunExp_TryInjectSolarEventMapCard)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetVar", SunExp_GetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetVar", SunExp_SetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffLevel", SunExp_GetBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRadianceLevel", SunExp_GetRadianceLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealDamage", SunExp_DealDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddDamageDescription", SunExp_AddDamageDescription)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSparkDamage", SunExp_CalcSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlareCutDamage", SunExp_CalcFlareCutDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarSparkDamage", SunExp_CalcSolarSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownPressureDamage", SunExp_CalcCrownPressureDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownCoreFlashDamage", SunExp_CalcCrownCoreFlashDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlamePierceDamage", SunExp_CalcFlamePierceDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSmokeErosionDamage", SunExp_CalcSmokeErosionDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetEnemyTargets", SunExp_GetEnemyTargets)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfStatus", SunExp_IsSelfStatus)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetPrimaryTarget", SunExp_GetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetPrimaryTarget", SunExp_SetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusForBuff", SunExp_SetStatusForBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuff", SunExp_GetStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuffLevel", SunExp_GetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveStatusBuff", SunExp_RemoveStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusBuffLevel", SunExp_SetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddStatusBuff", SunExp_AddStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerStatusBuff", SunExp_TriggerStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurn", SunExp_TriggerBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurnAllEnemies", SunExp_TriggerBurnAllEnemies)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRandomEnemyTarget", SunExp_GetRandomEnemyTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBurnToRandomEnemy", SunExp_AddBurnToRandomEnemy)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveBuffStacks", SunExp_RemoveBuffStacks)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionCount", SunExp_GetCollectionCount)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionItem", SunExp_GetCollectionItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffTypeName", SunExp_GetBuffTypeName)
    SunExp_RegisterDynamicMethod(config, "SunExp_NormalizeBuffId", SunExp_NormalizeBuffId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedId", SunExp_IsPositiveBuffExcludedId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedItem", SunExp_IsPositiveBuffExcludedItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsNegativeBuffItem", SunExp_IsNegativeBuffItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffIdFromItem", SunExp_GetBuffIdFromItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffSummary", SunExp_GetNegativeBuffSummary)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffTotal", SunExp_GetNegativeBuffTotal)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveAllNegativeBuffs", SunExp_RemoveAllNegativeBuffs)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasNegativeBuff", SunExp_HasNegativeBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasCrownPhase", SunExp_HasCrownPhase)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsBurnWardPending", SunExp_IsBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetBurnWardPending", SunExp_SetBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfBurnProtected", SunExp_IsSelfBurnProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearSelfBurnIfProtected", SunExp_ClearSelfBurnIfProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplySelfBurn", SunExp_ApplySelfBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_RegisterHook", SunExp_RegisterHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsHookTokenActive", SunExp_IsHookTokenActive)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearHook", SunExp_ClearHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_FlamewheelKey", SunExp_FlamewheelKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetFlamewheelUsed", SunExp_GetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetFlamewheelUsed", SunExp_SetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_UpdateFlamewheelCost", SunExp_UpdateFlamewheelCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsFlamewheelCardItem", SunExp_IsFlamewheelCardItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_RefreshFlamewheelCosts", SunExp_RefreshFlamewheelCosts)
end
