using AuraToolsExp.Dll.Config;
using AuraToolsExp.Dll.Features.DamageMeter.Model;
using AuraToolsExp.Dll.Features.DamageMeter;
using AuraToolsExp.Dll.Features.DamageMeter.Capture;
using AuraToolsExp.Dll.Features.DamageMeter.Network;
using AuraToolsExp.Dll.Features.Cg;
using AuraToolsExp.Dll.Features.CardRefresh;
using AuraToolsExp.Dll.Features.ModSync;
using AuraToolsExp.Dll.Features.PixelEmoji;
using AuraToolsExp.Dll.Features.SafeBox;
using AuraToolsExp.Dll.Features.StarterDeck;
using AuraToolsExp.Dll.Infrastructure;
using AuraSkin.Shared.Models;
using Newtonsoft.Json;
using static AuraToolsTestSuite;

assertions = 0;
if (args.Length == 3 && args[0] == "--benchmark-replay")
{
    MeasureReplayRecording(args[1], args[2]);
    return;
}
if (args.Length == 2 && args[0] == "--suite" && args[1] == "replay")
{
    TestMatchRecordDatabase();
    TestMatchReplayV17Core();
    TestReplayCaptureIteration();
    TestReplayHandLifecycle();
    TestReplayActionOwnerGeneration();
    TestMatchReplayModuleCompatibility();
    TestReplayExtensionIntentVisuals();
    TestMatchReplayLifecycleAndLibraryReturn();
    TestMatchReplayNativeAudioCallTracking();
    TestMatchReplayPackage();
    TestBackgroundWorkOwnerCancellation();
    TestBackgroundReplacementAdmission();
    TestReplayBackgroundPersistence();
    TestReplayReplicationAudience();
    TestIncomingReplayRecovery();
    TestOrderedQueueBudgets();
    Console.WriteLine($"AuraTools replay suite passed: {assertions} assertions.");
    return;
}

TestRoundAndDpt();
TestShieldViewRecalculation();
TestSnapshotRecovery();
TestSequenceAndSessionGuards();
TestLongRunningTotals();
TestRunAggregateSurvivesHistoryRetention();
TestFilteringAndGrandTotal();
TestDetailLimit();
TestAdventureHistory();
TestAdventureArchiveDatabase();
TestPlayerContentIdentity();
TestBestHitAndScientificFormat();
TestOutOfRunHistoryBuilder();
TestDeterministicAllocation();
TestDamageHistoryDatabase();
TestMatchRecordDatabase();
TestMatchReplayV17Core();
TestMatchReplayModuleCompatibility();
TestReplayExtensionIntentVisuals();
TestReplayCaptureIteration();
TestReplayHandLifecycle();
TestReplayActionOwnerGeneration();
TestMatchReplayRenderHostContract();
TestMatchReplayLifecycleAndLibraryReturn();
TestMatchReplayNativeAudioCallTracking();
TestMatchAnalysis();
TestMatchReplayExportPolicy();
TestMatchReplayPackage();
TestDamageMeterSettingsNormalization();
TestMatchRecordSettingsMigration();
TestConfigModelSerializationCompatibility();
TestPresentationOwnershipMigrations();
TestCardVisualRenderTargetPolicy();
TestPixelEmojiCore();
TestCardRefreshSettingsAndPoolPolicy();
TestLoggingSettingsNormalization();
TestUnifiedEventCgSettingsAndLegacyMigration();
TestRoleCgContextSelections();
TestRoleCgSkillIdentityAliases();
TestLowHealthNativePresentationLatch();
TestCgOutcomeReasonPolicy();
TestCgSettingsLayoutBudgets();
TestTeamScenePlanning();
TestEventCgArtCatalog();
TestSkillCgPresentationNormalization();
TestFeastRoleResourceIdentity();
TestSkinRemoteSelectionPolicy();
TestSafeBoxDataCompatibility();
TestRpcPayloadBudgetUsesUtf8Bytes();
TestProtocolCompatibilityContracts();
TestModSyncRequestTracker();
TestDamageMeterAuthorityPolicy();
TestDamageCaptureFrameWindow();
TestDamageCaptureMatchingPolicy();
TestDamageEventFactory();
TestDamageMeterHookRegistrationSet();
TestDamageMeterHudPresenter();
TestStarterDeckCardClassification();
TestStarterDeckDeckBuilder();
TestBundledFoundationRegistrationPlanner();
TestBundledFoundationModelLayout();
TestAutoBattleTechnicalFallbackState();
TestAuraToolModuleCatalogAndStateStore();
TestAuraRoutedHookOwnershipAndLeases();
TestAuraToolsHookOwnerActivation();
TestBackgroundWorkOwnerCancellation();
TestBackgroundReplacementAdmission();
TestInitializationDependencies();
TestModuleConfigCommitRollback();
TestReplayBackgroundPersistence();
TestReplayReplicationAudience();
TestIncomingReplayRecovery();
TestOrderedQueueBudgets();
TestNativeContentVisibilityLease();
TestToolboxTooltipPlacementPolicy();
TestPreparationDockLayoutPolicy();

Console.WriteLine($"AuraToolsExp tests passed: {assertions} assertions.");
return;
