using AuraToolsExp.Dll.Config;
using AuraToolsExp.Dll.Features.DamageMeter.Model;
using AuraToolsExp.Dll.Features.DamageMeter;
using AuraToolsExp.Dll.Features.DamageMeter.Capture;
using AuraToolsExp.Dll.Features.DamageMeter.Network;
using AuraToolsExp.Dll.Features.DamageMeter.SettlementCg;
using AuraToolsExp.Dll.Features.CardRefresh;
using AuraToolsExp.Dll.Features.ModSync;
using AuraToolsExp.Dll.Features.PixelEmoji;
using AuraToolsExp.Dll.Features.SafeBox;
using AuraToolsExp.Dll.Features.StarterDeck;
using AuraToolsExp.Dll.Infrastructure;
using AuraSkin.Shared.Models;
using Newtonsoft.Json;
using static AuraToolsTestSuite;

assertions = 0;

TestRoundAndDpt();
TestShieldViewRecalculation();
TestSnapshotRecovery();
TestSequenceAndSessionGuards();
TestLongRunningTotals();
TestRunAggregateSurvivesHistoryRetention();
TestFilteringAndGrandTotal();
TestDetailLimit();
TestAdventureHistory();
TestBestHitAndScientificFormat();
TestOutOfRunHistoryBuilder();
TestDeterministicAllocation();
TestDamageHistoryDatabase();
TestMatchRecordDatabase();
TestMatchReplayRuntimeCore();
TestMatchAnalysis();
TestMatchReplayExportPolicy();
TestMjpegAviWriter();
TestMatchReplayPackage();
TestDamageMeterSettingsNormalization();
TestMatchRecordSettingsMigration();
TestConfigModelSerializationCompatibility();
TestPixelEmojiCore();
TestCardRefreshSettingsAndPoolPolicy();
TestLoggingSettingsNormalization();
TestDamageSettlementCgSettingsAndLayout();
TestDamageSettlementCgPayloadOrdering();
TestDamageSettlementCgAnimationSpec();
TestDamageSettlementCgPreparationPolicy();
TestSkillCgPresentationNormalization();
TestFeastRoleResourceIdentity();
TestSkinRemoteSelectionPolicy();
TestSafeBoxDataCompatibility();
TestRpcPayloadBudgetUsesUtf8Bytes();
TestProtocolCompatibilityContracts();
TestModSyncRequestTracker();
TestDamageMeterAuthorityPolicy();
TestDamageCaptureFrameWindow();
TestDamageCaptureMatchingPolicy();
TestDamageEventFactory();
TestDamageMeterHookRegistrationSet();
TestDamageMeterHudPresenter();
TestStarterDeckCardClassification();
TestStarterDeckDeckBuilder();
TestBundledFoundationRegistrationPlanner();
TestBundledFoundationModelLayout();
TestAutoBattleTechnicalFallbackState();
TestAuraToolModuleCatalogAndStateStore();
TestNativeContentVisibilityLease();

Console.WriteLine($"AuraToolsExp tests passed: {assertions} assertions.");
return;
