using AuraToolsExp.Dll.Config;
using AuraToolsExp.Dll.Features.DamageMeter.Model;
using AuraToolsExp.Dll.Features.DamageMeter;
using AuraToolsExp.Dll.Features.DamageMeter.Capture;
using AuraToolsExp.Dll.Features.DamageMeter.Network;
using AuraToolsExp.Dll.Features.Cg;
using AuraToolsExp.Dll.Features.CardRefresh;
using AuraToolsExp.Dll.Features.ModSync;
using AuraToolsExp.Dll.Features.PixelEmoji;
using AuraToolsExp.Dll.Features.SafeBox;
using AuraToolsExp.Dll.Features.StarterDeck;
using AuraToolsExp.Dll.Infrastructure;
using AuraSkin.Shared.Models;
using Newtonsoft.Json;
using static AuraToolsTestSuite;

assertions = 0;

TestRoundAndDpt();
TestShieldViewRecalculation();
TestSnapshotRecovery();
TestSequenceAndSessionGuards();
TestLongRunningTotals();
TestRunAggregateSurvivesHistoryRetention();
TestFilteringAndGrandTotal();
TestDetailLimit();
TestAdventureHistory();
TestAdventureArchiveDatabase();
TestPlayerContentIdentity();
TestBestHitAndScientificFormat();
TestOutOfRunHistoryBuilder();
TestDeterministicAllocation();
TestDamageHistoryDatabase();
TestMatchRecordDatabase();
TestMatchReplayV12Core();
TestMatchReplayLifecycleAndLibraryReturn();
TestMatchReplayNativeAudioCallTracking();
TestMatchAnalysis();
TestMatchReplayExportPolicy();
TestMatchReplayPackage();
TestDamageMeterSettingsNormalization();
TestMatchRecordSettingsMigration();
TestConfigModelSerializationCompatibility();
TestPresentationOwnershipMigrations();
TestCardVisualRenderTargetPolicy();
TestPixelEmojiCore();
TestCardRefreshSettingsAndPoolPolicy();
TestLoggingSettingsNormalization();
TestUnifiedEventCgSettingsAndLegacyMigration();
TestRoleCgContextSelections();
TestCgOutcomeReasonPolicy();
TestCgSettingsLayoutBudgets();
TestTeamScenePlanning();
TestUnifiedCgAnimationSpec();
TestSkillCgPresentationNormalization();
TestFeastRoleResourceIdentity();
TestSkinRemoteSelectionPolicy();
TestSafeBoxDataCompatibility();
TestRpcPayloadBudgetUsesUtf8Bytes();
TestProtocolCompatibilityContracts();
TestModSyncRequestTracker();
TestDamageMeterAuthorityPolicy();
TestDamageCaptureFrameWindow();
TestDamageCaptureMatchingPolicy();
TestDamageEventFactory();
TestDamageMeterHookRegistrationSet();
TestDamageMeterHudPresenter();
TestStarterDeckCardClassification();
TestStarterDeckDeckBuilder();
TestBundledFoundationRegistrationPlanner();
TestBundledFoundationModelLayout();
TestAutoBattleTechnicalFallbackState();
TestAuraToolModuleCatalogAndStateStore();
TestAuraRoutedHookOwnershipAndLeases();
TestAuraToolsHookOwnerActivation();
TestBackgroundWorkOwnerCancellation();
TestNativeContentVisibilityLease();
TestToolboxTooltipPlacementPolicy();
TestPreparationDockLayoutPolicy();

Console.WriteLine($"AuraToolsExp tests passed: {assertions} assertions.");
return;
