<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Aura.Shared">
      <HintPath>..\SunExp\Scripts\Aura.Shared.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SunExp.Aura">
      <HintPath>..\SunExp-Dev\bin\Release\net472\SunExp.Aura.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Managed\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
