param(
    [string]$SourceRoot = "",
    [string]$ManifestPath = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    return (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
}

function Write-Utf8NoBom {
    param(
        [string]$Path,
        [string]$Text
    )
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Text, $encoding)
}

$repoRoot = Get-RepoRoot
if (-not $SourceRoot) {
    $SourceRoot = Join-Path $repoRoot "SunExp\Scripts\_src"
}
elseif (-not [System.IO.Path]::IsPathRooted($SourceRoot)) {
    $SourceRoot = Join-Path $repoRoot $SourceRoot
}

$sourceRootPath = (Resolve-Path -LiteralPath $SourceRoot).Path

if (-not $ManifestPath) {
    $ManifestPath = Join-Path $sourceRootPath "manifest.txt"
}
elseif (-not [System.IO.Path]::IsPathRooted($ManifestPath)) {
    $ManifestPath = Join-Path $repoRoot $ManifestPath
}

if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot "SunExp\Scripts\Entry.lua"
}
elseif (-not [System.IO.Path]::IsPathRooted($OutputPath)) {
    $OutputPath = Join-Path $repoRoot $OutputPath
}

$manifestPathResolved = (Resolve-Path -LiteralPath $ManifestPath).Path
$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory | Out-Null
}

$modules = New-Object System.Collections.Generic.List[string]
foreach ($line in Get-Content -LiteralPath $manifestPathResolved -Encoding UTF8) {
    $entry = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($entry) -or $entry.StartsWith("#")) {
        continue
    }
    $modules.Add($entry) | Out-Null
}

if ($modules.Count -eq 0) {
    throw "No modules listed in '$manifestPathResolved'."
}

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add("-- Generated by tools/Build-SunExpEntry.ps1 from SunExp/Scripts/_src.") | Out-Null
$parts.Add("-- Edit the _src modules, then rebuild this file.") | Out-Null
$parts.Add("-- The game runtime only guarantees Scripts/Entry.lua as the mod load entry.") | Out-Null
$parts.Add("") | Out-Null

foreach ($module in $modules) {
    $modulePath = Join-Path $sourceRootPath $module
    if (-not (Test-Path -LiteralPath $modulePath)) {
        throw "Module '$module' was listed in manifest but not found at '$modulePath'."
    }

    $content = Get-Content -Raw -LiteralPath $modulePath -Encoding UTF8
    $content = $content.TrimEnd("`r", "`n")

    $parts.Add("do") | Out-Null
    $parts.Add("-- <module: $module>") | Out-Null
    $parts.Add($content) | Out-Null
    $parts.Add("-- </module: $module>") | Out-Null
    $parts.Add("end") | Out-Null
    $parts.Add("") | Out-Null
}

$output = ($parts -join "`r`n").TrimEnd("`r", "`n") + "`r`n"
Write-Utf8NoBom -Path $OutputPath -Text $output

Write-Host "Built $OutputPath from $($modules.Count) module(s)."
