-- Generated by tools/Build-SunExpEntry.ps1 from SunExp/Scripts/_src.
-- Edit the _src modules, then rebuild this file.
-- The game runtime only guarantees Scripts/Entry.lua as the mod load entry.

do
-- <module: core/vars.lua>
function SunExp_GetVar(self, key, defaultValue)
    if self == nil or self.Vars == nil or not self.Vars:ContainsKey(key) then
        return defaultValue
    end
    return self.Vars:get_Item(key)
end

function SunExp_SetVar(self, key, value)
    if self == nil or self.Vars == nil then
        return
    end
    self.Vars:set_Item(key, tostring(value))
end
-- </module: core/vars.lua>
end

do
-- <module: core/player.lua>
function SunExp_PlayerInfo()
    if CS == nil or CS.ScriptExecutor == nil then
        return nil
    end
    return CS.ScriptExecutor.PlayerInfo
end

function SunExp_PlayerGetVar(key, defaultValue)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return defaultValue
    end
    local ok, value = pcall(function()
        return player.GetGameVar(key)
    end)
    if ok and value ~= nil and tostring(value) ~= "" then
        return tostring(value)
    end
    return defaultValue
end

function SunExp_PlayerSetVar(key, value)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local ok = pcall(function()
        player.SetGameVar(key, tostring(value))
    end)
    return ok
end

function SunExp_GainGold(amount)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local value = math.floor(tonumber(amount) or 0)
    if value == 0 then
        return true
    end
    local ok = pcall(function()
        player.Money = (tonumber(player.Money) or 0) + value
    end)
    return ok
end

function SunExp_AddCardReward(cardId)
    local player = SunExp_PlayerInfo()
    if player == nil or cardId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddCard(cardId)
    end)
    return ok
end

function SunExp_AddRelicReward(relicId)
    local player = SunExp_PlayerInfo()
    if player == nil or relicId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddRelic(relicId)
    end)
    return ok
end

function SunExp_AddBlessReward(blessId)
    local player = SunExp_PlayerInfo()
    if player == nil or blessId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddBless(blessId)
    end)
    return ok
end

function SunExp_EndEvent()
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local ok = pcall(function()
        player.EndEvent()
    end)
    return ok
end

function SunExp_ShowCaption(text)
    local player = SunExp_PlayerInfo()
    if player == nil or text == nil then
        return false
    end
    local ok = pcall(function()
        player.ShowCaption(text)
    end)
    return ok
end
-- </module: core/player.lua>
end

do
-- <module: events/wuna_solar_event.lua>
function SunExp_WunaProgressKey()
    return "SunExp_WunaEventProgressV2"
end

function SunExp_GetWunaProgress()
    return tonumber(SunExp_PlayerGetVar(SunExp_WunaProgressKey(), "0")) or 0
end

function SunExp_SetWunaProgress(progress)
    return SunExp_PlayerSetVar(SunExp_WunaProgressKey(), tostring(progress))
end

function SunExp_WunaLevelKey()
    return "SunExp_WunaEventLevelV2"
end

function SunExp_GetCurrentMapLevel()
    local level = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            level = CS.MapManager.Instance.Level
        end
    end)
    return tostring(level or "unknown")
end

function SunExp_GetCurrentMapLevelNumber()
    local level = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            level = CS.MapManager.Instance.Level
        end
    end)
    if level == nil then
        pcall(function()
            if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil and CS.MapManager.Instance.ModeMapManager ~= nil then
                level = CS.MapManager.Instance.ModeMapManager.Level
            end
        end)
    end
    return tonumber(level) or 0
end

function SunExp_HasWunaEventInCurrentLevel()
    return false
end

function SunExp_MarkWunaEventInCurrentLevel()
    return true
end

function SunExp_AdvanceWunaEvent(progress)
    local current = SunExp_GetWunaProgress()
    local nextProgress = math.max(current, tonumber(progress) or current)
    SunExp_SetWunaProgress(nextProgress)
end

function SunExp_WunaFinish(progress)
    SunExp_AdvanceWunaEvent(progress)
    SunExp_EndEvent()
end

function SunExp_TrySetEventChoiceVar(vars, key, value)
    if vars == nil or key == nil then
        return false
    end
    local text = tostring(value)
    local ok = pcall(function()
        vars:set_Item(key, text)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars[key] = text
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars:Set(key, text)
    end)
    return ok
end

function SunExp_SetEventChoices(executor, choice1, choice2, choice3, choice4)
    local vars = nil
    if executor ~= nil then
        pcall(function()
            vars = executor.Vars
        end)
    end
    if vars == nil then
        pcall(function()
            if Vars ~= nil then
                vars = Vars
            end
        end)
    end
    if vars == nil then
        return false
    end
    local choices = { choice1, choice2, choice3, choice4 }
    local changed = false
    for i = 1, 4 do
        local value = "0"
        if choices[i] ~= nil and tostring(choices[i]) ~= "" then
            value = choices[i]
        end
        changed = SunExp_TrySetEventChoiceVar(vars, "Choice" .. tostring(i), value) or changed
    end
    return changed
end

function SunExp_BeginWunaRepeatEvent(executor)
    return SunExp_SetEventChoices(executor, "1")
end

function SunExp_BeginWunaEvent(executor, step)
    local expected = math.max(1, math.min(6, tonumber(step) or 1))
    local current = SunExp_GetWunaProgress()
    if current ~= expected - 1 then
        return SunExp_BeginWunaRepeatEvent(executor)
    end
    return SunExp_SetEventChoices(executor, "1", "1")
end

function SunExp_WunaRewardCard(progress, cardId)
    SunExp_GainGold(100)
    SunExp_AddCardReward(cardId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardRelic(progress, relicId)
    SunExp_GainGold(100)
    SunExp_AddRelicReward(relicId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardBless(progress, blessId)
    SunExp_GainGold(100)
    SunExp_AddBlessReward(blessId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardNone(progress)
    SunExp_GainGold(100)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRepeatReward()
    SunExp_AddBlessReward("blessing_8")
    SunExp_EndEvent()
end

function SunExp_SolarEventMapId()
    return "SunExp_sunexp_solar_event"
end

function SunExp_SolarEventPlaceholderNodeId()
    return "SunExp_sunexp_solar_event"
end

function SunExp_IsSolarEventMapId(id)
    if id == nil then
        return false
    end
    local value = tostring(id)
    return value == "SunExp_sunexp_solar_event" or value == "solar_event"
end

function SunExp_IsSolarEventPlaceholderNodeId(id)
    return SunExp_IsSolarEventMapId(id)
end

function SunExp_GetCurrentSolarEventId()
    if SunExp_GetWunaProgress() >= 6 then
        return "SunExp_sunexp_Sub_wuna_event_repeat"
    end
    local nextEvent = math.min(6, math.max(1, SunExp_GetWunaProgress() + 1))
    return string.format("SunExp_sunexp_Sub_wuna_event_%02d", nextEvent)
end

function SunExp_TryGetHookField(obj, fieldName)
    if obj == nil or fieldName == nil then
        return nil
    end
    local ok, value = pcall(function()
        return obj[fieldName]
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return obj:get_Item(fieldName)
    end)
    if ok and value ~= nil then
        return value
    end
    return nil
end

function SunExp_TryGetHookArguments(obj)
    return SunExp_TryGetHookField(obj, "Arguments")
end

function SunExp_TryGetHookTarget(obj)
    return SunExp_TryGetHookField(obj, "Target")
end

function SunExp_TrySetNodeData(node, key, value)
    if node == nil or node.data == nil or key == nil then
        return false
    end
    local text = tostring(value)
    local ok = pcall(function()
        node.data:set_Item(key, text)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        node.data[key] = text
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        node.data:Set(key, text)
    end)
    return ok
end

function SunExp_TryGetNodeDataValue(node, key)
    if node == nil or node.data == nil or key == nil then
        return nil
    end
    local ok, value = pcall(function()
        if node.data.ContainsKey ~= nil and not node.data:ContainsKey(key) then
            return nil
        end
        return node.data:get_Item(key)
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return node.data[key]
    end)
    if ok then
        return value
    end
    return nil
end

function SunExp_IsSolarEventNode(node)
    return SunExp_IsSolarEventMapId(SunExp_TryGetNodeDataValue(node, "Id"))
end

function SunExp_IsEventNode(node)
    local typeName = SunExp_TryGetNodeDataValue(node, "Type")
    if typeName ~= nil and tostring(typeName) == "Event" then
        return true
    end
    local nodeType = nil
    pcall(function()
        nodeType = node.type
    end)
    return tostring(nodeType or "") == "Event"
end

function SunExp_GetMapTree(treeOrManager)
    if treeOrManager == nil then
        return nil
    end
    local tree = nil
    pcall(function()
        tree = treeOrManager.MapTree
    end)
    if tree ~= nil then
        return tree
    end
    pcall(function()
        tree = treeOrManager.mapTree
    end)
    if tree ~= nil then
        return tree
    end
    return treeOrManager
end

function SunExp_GetCurrentMapTree()
    local tree = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            tree = CS.MapManager.Instance.MapTree
        end
    end)
    if tree ~= nil then
        return tree
    end
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil and CS.MapManager.Instance.ModeMapManager ~= nil then
            tree = CS.MapManager.Instance.ModeMapManager.MapTree
        end
    end)
    return tree
end

function SunExp_GetSolarLayerSegmentSize()
    local exDelete = 0
    if SunExp_TestExDeleteDes ~= nil then
        exDelete = tonumber(SunExp_TestExDeleteDes) or 0
    else
        pcall(function()
            if CS ~= nil and CS.GameSaveManager ~= nil and CS.GameVar ~= nil then
                exDelete = tonumber(CS.GameSaveManager.GetValue(CS.GameVar.ExDeleteDes)) or exDelete
            end
        end)
        pcall(function()
            if CS ~= nil and CS.GameSaveManager ~= nil then
                exDelete = tonumber(CS.GameSaveManager.GetValue("ExDeleteDes")) or exDelete
            end
        end)
    end
    local size = 8 - exDelete
    if size < 1 then
        return 1
    end
    return size
end

function SunExp_GetSolarLayerStartIndex()
    local level = SunExp_GetCurrentMapLevelNumber()
    return math.floor(level / 6) * SunExp_GetSolarLayerSegmentSize()
end

function SunExp_GetSolarLayerRange()
    return SunExp_GetSolarLayerStartIndex(), SunExp_GetSolarLayerSegmentSize()
end

function SunExp_CreateSolarEventNode(treeOrManager)
    local tree = SunExp_GetMapTree(treeOrManager)
    if tree == nil then
        tree = SunExp_GetCurrentMapTree()
    end
    local node = nil
    pcall(function()
        if tree ~= nil and tree.GetNodeByNodeId ~= nil then
            node = tree:GetNodeByNodeId(SunExp_SolarEventPlaceholderNodeId())
        end
    end)
    if node == nil then
        pcall(function()
            node = CS.MapTree.Node.New("Event")
        end)
    end
    if node == nil then
        return nil
    end
    if node.data == nil then
        return nil
    end
    pcall(function()
        node.type = "Event"
    end)
    SunExp_TrySetNodeData(node, "Id", SunExp_SolarEventMapId())
    SunExp_TrySetNodeData(node, "Type", "Event")
    SunExp_TrySetNodeData(node, "NodeId", SunExp_GetCurrentSolarEventId())
    SunExp_TrySetNodeData(node, "Level", "-1")
    return node
end

function SunExp_GetSelectNodes(treeOrManager)
    local tree = SunExp_GetMapTree(treeOrManager)
    if tree == nil then
        tree = SunExp_GetCurrentMapTree()
    end
    local nodes = nil
    pcall(function()
        if tree ~= nil then
            nodes = tree.SelectNode
        end
    end)
    return nodes
end

function SunExp_IsBreakNode(node)
    local nodeId = SunExp_TryGetNodeDataValue(node, "NodeId")
    if nodeId ~= nil and string.find(tostring(nodeId), "Breaks", 1, true) ~= nil then
        return true
    end
    local id = SunExp_TryGetNodeDataValue(node, "Id")
    if id ~= nil and string.find(tostring(id), "Breaks", 1, true) ~= nil then
        return true
    end
    return false
end

function SunExp_IsProtectedFixedEventNode(node)
    local nodeId = SunExp_TryGetNodeDataValue(node, "NodeId")
    if nodeId == nil then
        return false
    end
    local value = tostring(nodeId)
    return value == "event_2001"
        or value == "event_2002"
        or value == "event_2003"
        or value == "event_2004"
        or value == "event_2005"
        or value == "event_2006"
        or value == "event_2015"
        or value == "event_999"
end

function SunExp_TrySetSolarEventNode(node)
    if node == nil or node.data == nil then
        return false
    end
    local changed = false
    changed = SunExp_TrySetNodeData(node, "Id", SunExp_SolarEventMapId()) or changed
    changed = SunExp_TrySetNodeData(node, "Type", "Event") or changed
    changed = SunExp_TrySetNodeData(node, "NodeId", SunExp_GetCurrentSolarEventId()) or changed
    changed = SunExp_TrySetNodeData(node, "Level", "-1") or changed
    pcall(function()
        node.type = "Event"
    end)
    return changed
end

function SunExp_TryReplaceNodeAt(collection, index, replacement)
    if SunExp_TrySetCollectionItem(collection, index, replacement) then
        return true
    end
    return false
end

function SunExp_EnsureSolarEventInCurrentLayer(treeOrManager)
    local nodes = SunExp_GetSelectNodes(treeOrManager)
    if nodes == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    if count <= 0 then
        return false
    end
    local startIndex, segmentSize = SunExp_GetSolarLayerRange()
    if startIndex >= count then
        return false
    end
    local endIndex = math.min(count - 1, startIndex + segmentSize - 1)
    local firstEventIndex = nil
    local firstFallbackIndex = nil
    for i = startIndex, endIndex do
        local node = SunExp_GetCollectionItem(nodes, i)
        if SunExp_IsSolarEventNode(node) then
            return SunExp_TrySetSolarEventNode(node)
        end
        if node ~= nil and not SunExp_IsBreakNode(node) and not SunExp_IsProtectedFixedEventNode(node) then
            if firstFallbackIndex == nil then
                firstFallbackIndex = i
            end
            if firstEventIndex == nil and SunExp_IsEventNode(node) then
                firstEventIndex = i
            end
        end
    end
    local replaceIndex = firstEventIndex or firstFallbackIndex
    if replaceIndex == nil then
        return false
    end
    local node = SunExp_CreateSolarEventNode(treeOrManager)
    if node == nil then
        node = SunExp_GetCollectionItem(nodes, replaceIndex)
        if not SunExp_TrySetSolarEventNode(node) then
            return false
        end
        return true
    end
    if SunExp_TryReplaceNodeAt(nodes, replaceIndex, node) then
        return true
    end
    return SunExp_TrySetSolarEventNode(SunExp_GetCollectionItem(nodes, replaceIndex))
end

function SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local target = SunExp_TryGetHookTarget(context)
            if target == nil then
                target = context
            end
            if SunExp_EnsureSolarEventInCurrentLayer(target) then
                changed = true
            end
        end
    end)
    return changed
end

function SunExp_TryAddCollectionItem(collection, value)
    if collection == nil or value == nil then
        return false
    end
    local ok = pcall(function()
        collection:Add(value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        table.insert(collection, value)
    end)
    return ok
end

function SunExp_TryReplaceFirstEventNode(nodes, replacement)
    if nodes == nil or replacement == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        local node = SunExp_GetCollectionItem(nodes, i)
        if SunExp_IsEventNode(node) then
            return SunExp_TrySetCollectionItem(nodes, i, replacement)
        end
    end
    return false
end

function SunExp_TryAppendSolarEventNode(nodes, treeOrManager)
    if nodes == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        if SunExp_IsSolarEventNode(SunExp_GetCollectionItem(nodes, i)) then
            return false
        end
    end
    local node = SunExp_CreateSolarEventNode(treeOrManager)
    if node == nil then
        return false
    end
    if SunExp_TryAddCollectionItem(nodes, node) then
        return true
    end
    return SunExp_TryReplaceFirstEventNode(nodes, node)
end

function SunExp_TryAppendSolarEventNodeFromHook(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local target = SunExp_TryGetHookTarget(context)
            local hookArgs = SunExp_TryGetHookArguments(context)
            local count = SunExp_GetCollectionCount(hookArgs)
            for j = 0, count - 1 do
                if SunExp_TryAppendSolarEventNode(SunExp_GetCollectionItem(hookArgs, j), target) then
                    changed = true
                    return
                end
            end
            if hookArgs == nil and SunExp_TryAppendSolarEventNode(context, target) then
                changed = true
                return
            end
        end
    end)
    return changed
end

function SunExp_TryRepairSolarEventNode(node)
    if SunExp_IsSolarEventNode(node) then
        return SunExp_TrySetSolarEventNode(node)
    end
    return false
end

function SunExp_TryRepairSolarEventNodes(nodes)
    if nodes == nil then
        return false
    end
    local changed = false
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        changed = SunExp_TryRepairSolarEventNode(SunExp_GetCollectionItem(nodes, i)) or changed
    end
    return changed
end

function SunExp_TryRepairSolarEventSyncedMapData()
    return false
end

function SunExp_TryRepairSolarEventSelectedNodesFromHook(...)
    return SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
end

function SunExp_TryRepairSolarEventGeneratedMap(...)
    return SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
end

function SunExp_GetMapSelectSolarChoiceCounts(ui)
    return 0, 0
end

function SunExp_TryCreateSolarEventChoiceUI(ui)
    return false
end

function SunExp_TryAppendSolarEventChoiceForUI(ui)
    return false
end

function SunExp_TryAppendSolarEventChoiceUI(...)
    return false
end

function SunExp_TryRepairSolarEventMapArrays(maps, mapdata)
    if maps == nil or mapdata == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(maps)
    if count <= 0 then
        return false
    end
    local changed = false
    for i = 0, count - 1 do
        local mapId = SunExp_GetCollectionItem(maps, i)
        if SunExp_IsSolarEventMapId(mapId) then
            SunExp_TrySetCollectionItem(maps, i, SunExp_SolarEventMapId())
            changed = SunExp_TrySetCollectionItem(mapdata, i, SunExp_GetCurrentSolarEventId()) or changed
        end
    end
    return changed
end

function SunExp_TryRepairSolarEventMapSelection(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local hookArgs = SunExp_TryGetHookArguments(context)
            if hookArgs == nil then
                hookArgs = context
            end
            local count = SunExp_GetCollectionCount(hookArgs)
            for j = 0, count - 2 do
                local maps = SunExp_GetCollectionItem(hookArgs, j)
                local mapdata = SunExp_GetCollectionItem(hookArgs, j + 1)
                if SunExp_TryRepairSolarEventMapArrays(maps, mapdata) then
                    changed = true
                end
            end
        end
    end)
    return changed
end

function SunExp_TryRepairSolarEventLoadArgumentList(arguments)
    return false
end

function SunExp_TryRepairSolarEventLoad(...)
    return false
end
-- </module: events/wuna_solar_event.lua>
end

do
-- <module: combat/damage.lua>
function SunExp_GetBuffLevel(self, buffId)
    if self == nil or self.Self == nil then
        return 0
    end
    local buff = self.Self:GetBuff(buffId)
    if buff == nil or buff.buffConfig == nil or buff.buffConfig.Level == nil then
        return 0
    end
    return tonumber(buff.buffConfig.Level) or buff.buffConfig.Level or 0
end

function SunExp_GetRadianceLevel(self)
    return SunExp_GetBuffLevel(self, "SunExp_sunexp_solar_radiance")
end

function SunExp_DealDamage(self, amount)
    if self == nil then
        return false
    end
    local damage = math.floor(tonumber(amount) or 0)
    if damage <= 0 then
        return false
    end
    self:Damage(tostring(damage))
    return true
end

function SunExp_AddDamageDescription(self, index, amount)
    if self == nil then
        return 0
    end
    local damage = math.floor(tonumber(amount) or 0)
    if damage < 0 then
        damage = 0
    end
    pcall(function()
        self:AddDescription(tostring(index), "Damage", tostring(damage))
    end)
    return damage
end

function SunExp_CalcSparkDamage(self)
    return 5
end

function SunExp_CalcFlareCutDamage(self)
    local level = SunExp_GetRadianceLevel(self)
    local damage = 10 + level
    if SunExp_HasCrownPhase(self, 4) then
        damage = damage + level
    end
    return damage
end

function SunExp_CalcSolarSparkDamage(self)
    local useFlame = math.min(5, SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame"))
    local radLevel = SunExp_GetRadianceLevel(self)
    local damage = 6 + useFlame * 4
    if SunExp_HasCrownPhase(self, 4) then
        damage = damage + radLevel * 2
    end
    return damage
end

function SunExp_CalcCrownPressureDamage(self)
    if not SunExp_HasCrownPhase(self, 4) then
        return 0
    end
    local radLevel = SunExp_GetRadianceLevel(self)
    local fieldLevel = SunExp_GetBuffLevel(self, "SunExp_sunexp_scorching_canopy")
    return radLevel * 2 + fieldLevel * 5
end

function SunExp_CalcCrownCoreFlashDamage(self)
    local flameCount = SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame")
    local useRad = math.floor(SunExp_GetRadianceLevel(self) / 2)
    return 40 + flameCount * 5 + useRad * 10
end

function SunExp_CalcFlamePierceDamage(self)
    local target = SunExp_GetPrimaryTarget(self)
    local burnLevel = SunExp_GetStatusBuffLevel(target, "buff_burn")
    local flameLevel = SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame")
    local mult = math.max(1, math.floor(flameLevel / 4))
    return 8 + burnLevel * mult
end

function SunExp_CalcSmokeErosionDamage(self)
    local target = SunExp_GetPrimaryTarget(self)
    return 7 + SunExp_GetStatusBuffLevel(target, "buff_burn")
end
-- </module: combat/damage.lua>
end

do
-- <module: combat/targeting.lua>
function SunExp_GetEnemyTargets(self)
    local targets = {}
    if self == nil then
        return targets
    end
    pcall(function()
        self:SetStatus("AllTarget")
    end)
    if self.Object == nil then
        return targets
    end
    local count = SunExp_GetCollectionCount(self.Object)
    for i = 0, count - 1 do
        local target = SunExp_GetCollectionItem(self.Object, i)
        if target ~= nil and not SunExp_IsSelfStatus(self, target) then
            table.insert(targets, target)
        end
    end
    return targets
end

function SunExp_IsSelfStatus(self, target)
    return self ~= nil and self.Self ~= nil and target ~= nil and target.InstanceId ~= nil and self.Self.InstanceId == target.InstanceId
end

function SunExp_GetPrimaryTarget(self)
    if self == nil then
        return nil
    end
    if self.Target ~= nil and not SunExp_IsSelfStatus(self, self.Target) then
        return self.Target
    end
    pcall(function()
        self:SetStatus("Target")
    end)
    if self.Object == nil or self.Object.Count == nil or self.Object.Count <= 0 then
        return nil
    end
    local ok, target = pcall(function()
        return self.Object:get_Item(0)
    end)
    if ok and target ~= nil and not SunExp_IsSelfStatus(self, target) then
        return target
    end
    return nil
end

function SunExp_SetPrimaryTarget(self, target)
    if self == nil or target == nil then
        return false
    end
    if target.InstanceId ~= nil then
        local ok = pcall(function()
            self:SetStatusById(target.InstanceId)
        end)
        if ok then
            return true
        end
    end
    pcall(function()
        self:SetStatus("Target")
    end)
    return false
end

function SunExp_SetStatusForBuff(self, target, fallbackStatus)
    if self == nil then
        return false
    end
    if target ~= nil then
        if SunExp_IsSelfStatus(self, target) then
            self:SetStatus("Self")
            return true
        end
        return SunExp_SetPrimaryTarget(self, target)
    end
    if fallbackStatus ~= nil then
        self:SetStatus(fallbackStatus)
        return true
    end
    return false
end

function SunExp_GetStatusBuff(target, buffId)
    if target == nil or buffId == nil then
        return nil
    end
    local ok, buff = pcall(function()
        return target:GetBuff(buffId)
    end)
    if ok then
        return buff
    end
    return nil
end

function SunExp_GetStatusBuffLevel(target, buffId)
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil or buff.buffConfig.Level == nil then
        return 0
    end
    return tonumber(buff.buffConfig.Level) or 0
end

function SunExp_RemoveStatusBuff(self, target, buffId, fallbackStatus)
    if self == nil or buffId == nil then
        return false
    end
    SunExp_SetStatusForBuff(self, target, fallbackStatus)
    local ok = pcall(function()
        self:RemoveBuff(buffId)
    end)
    if ok then
        return true
    end
    if target ~= nil then
        ok = pcall(function()
            target:RemoveBuff(buffId)
        end)
        return ok
    end
    return false
end

function SunExp_SetStatusBuffLevel(self, target, buffId, level)
    local nextLevel = tonumber(level) or 0
    if target == nil or buffId == nil then
        return false
    end
    if nextLevel <= 0 then
        return SunExp_RemoveStatusBuff(self, target, buffId)
    end
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil then
        return false
    end
    buff.buffConfig.Level = nextLevel
    return true
end

function SunExp_AddStatusBuff(self, target, buffId, amount, fallbackStatus)
    if self == nil or buffId == nil or amount == nil then
        return false
    end
    local before = SunExp_GetStatusBuffLevel(target, buffId)
    if not SunExp_SetStatusForBuff(self, target, fallbackStatus) then
        return false
    end
    local ok = pcall(function()
        self:AddBuff(buffId, tostring(amount))
    end)
    if target == nil then
        return ok
    end
    local after = SunExp_GetStatusBuffLevel(target, buffId)
    if after > before then
        return true
    end
    ok = pcall(function()
        target:AddBuff(buffId, tonumber(amount) or amount)
    end)
    after = SunExp_GetStatusBuffLevel(target, buffId)
    if ok and after > before then
        return true
    end
    ok = pcall(function()
        target:AddBuff(buffId, tostring(amount))
    end)
    return ok and SunExp_GetStatusBuffLevel(target, buffId) > before
end

function SunExp_TriggerStatusBuff(self, target, buffId, eventName, fallbackStatus)
    if self == nil or buffId == nil then
        return false
    end
    if target ~= nil and SunExp_GetStatusBuffLevel(target, buffId) <= 0 then
        return false
    end
    if not SunExp_SetStatusForBuff(self, target, fallbackStatus) then
        return false
    end
    local ok = pcall(function()
        self:RunImmediately(buffId, eventName or "StartRound")
    end)
    return ok
end

function SunExp_TriggerBurn(self, target, fallbackStatus)
    return SunExp_TriggerStatusBuff(self, target, "buff_burn", "StartRound", fallbackStatus)
end

function SunExp_TriggerBurnAllEnemies(self, times)
    if self == nil then
        return 0
    end
    local count = tonumber(times) or 1
    if count < 1 then
        count = 1
    end
    local triggered = 0
    for n = 1, count do
        self:SetStatus("AllTarget")
        local ok = pcall(function()
            self:RunImmediately("buff_burn", "StartRound")
        end)
        if ok then
            triggered = triggered + 1
        end
    end
    return triggered
end

function SunExp_GetRandomEnemyTarget(self, requireBurn)
    local targets = SunExp_GetEnemyTargets(self)
    local candidates = {}
    for i = 1, #targets do
        local target = targets[i]
        if not requireBurn or SunExp_GetStatusBuffLevel(target, "buff_burn") > 0 then
            table.insert(candidates, target)
        end
    end
    if #candidates == 0 then
        return nil
    end
    return candidates[math.random(1, #candidates)]
end

function SunExp_AddBurnToRandomEnemy(self, amount)
    local target = SunExp_GetRandomEnemyTarget(self, false)
    if target == nil then
        return false
    end
    return SunExp_AddStatusBuff(self, target, "buff_burn", amount)
end

function SunExp_RemoveBuffStacks(selfOrTarget, targetOrBuffId, buffIdOrAmount, amountOrNil)
    local executor = nil
    local target = selfOrTarget
    local buffId = targetOrBuffId
    local amount = buffIdOrAmount
    if amountOrNil ~= nil then
        executor = selfOrTarget
        target = targetOrBuffId
        buffId = buffIdOrAmount
        amount = amountOrNil
    end
    local count = tonumber(amount) or 0
    if target == nil or buffId == nil or count <= 0 then
        return 0
    end
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil then
        return 0
    end
    local level = tonumber(buff.buffConfig.Level) or 0
    local removed = math.min(level, count)
    if removed <= 0 then
        return 0
    end
    local nextLevel = level - removed
    if nextLevel <= 0 then
        if executor ~= nil then
            SunExp_RemoveStatusBuff(executor, target, buffId)
        else
            pcall(function()
                target:RemoveBuff(buffId)
            end)
        end
    else
        buff.buffConfig.Level = nextLevel
    end
    return removed
end
-- </module: combat/targeting.lua>
end

do
-- <module: core/collections.lua>
function SunExp_GetCollectionCount(collection)
    if collection == nil then
        return 0
    end
    local ok, count = pcall(function()
        return collection.Count
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return collection:Count()
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return collection.Length
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return #collection
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    return 0
end

function SunExp_GetCollectionItem(collection, index)
    if collection == nil then
        return nil
    end
    local ok, item = pcall(function()
        return collection:get_Item(index)
    end)
    if ok and item ~= nil then
        return item
    end
    ok, item = pcall(function()
        return collection[index]
    end)
    if ok and item ~= nil then
        return item
    end
    ok, item = pcall(function()
        return collection[index + 1]
    end)
    if ok and item ~= nil then
        return item
    end
    return nil
end

function SunExp_TrySetCollectionItem(collection, index, value)
    if collection == nil then
        return false
    end
    local ok = pcall(function()
        collection:set_Item(index, value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        collection[index] = value
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        collection[index + 1] = value
    end)
    return ok
end
-- </module: core/collections.lua>
end

do
-- <module: combat/negative_buffs.lua>
function SunExp_GetBuffTypeName(buff)
    if buff == nil or buff.buffConfig == nil then
        return nil
    end
    local ok, typeName = pcall(function()
        return buff.buffConfig.Type
    end)
    if ok and typeName ~= nil then
        return tostring(typeName)
    end
    if buff.buffConfig.dataConfig == nil or buff.buffConfig.dataConfig.data == nil then
        return nil
    end
    ok, typeName = pcall(function()
        local data = buff.buffConfig.dataConfig.data
        if data.ContainsKey ~= nil and not data:ContainsKey("Type") then
            return nil
        end
        return data:get_Item("Type")
    end)
    if ok and typeName ~= nil then
        return tostring(typeName)
    end
    return nil
end

SunExp_PositiveBuffExcludeIds = {
    solar_radiance = true,
    gathered_flame = true,
    scorching_canopy = true,
    ember_cloak = true,
    solar_crown = true,
    origin_core_radiance = true,
    cycle_gathered_flame = true,
    afterglow_omen = true
}

function SunExp_NormalizeBuffId(buffId)
    if buffId == nil then
        return nil
    end
    local id = tostring(buffId)
    local prefix = "SunExp_sunexp_"
    if string.sub(id, 1, string.len(prefix)) == prefix then
        return string.sub(id, string.len(prefix) + 1)
    end
    return id
end

function SunExp_IsPositiveBuffExcludedId(buffId)
    local id = SunExp_NormalizeBuffId(buffId)
    return id ~= nil and SunExp_PositiveBuffExcludeIds[id] == true
end

function SunExp_IsPositiveBuffExcludedItem(buff)
    return SunExp_IsPositiveBuffExcludedId(SunExp_GetBuffIdFromItem(buff))
end

function SunExp_IsNegativeBuffItem(buff)
    if SunExp_IsPositiveBuffExcludedItem(buff) then
        return false
    end
    local typeName = SunExp_GetBuffTypeName(buff)
    if typeName == nil then
        return false
    end
    return typeName == "负面" or typeName == "Negative" or string.find(typeName, "负面", 1, true) ~= nil
end

function SunExp_GetBuffIdFromItem(buff)
    if buff == nil or buff.buffConfig == nil then
        return nil
    end
    local ok, buffId = pcall(function()
        return buff.buffConfig.BuffId
    end)
    if ok and buffId ~= nil then
        return buffId
    end
    if buff.buffConfig.dataConfig == nil or buff.buffConfig.dataConfig.data == nil then
        return nil
    end
    ok, buffId = pcall(function()
        local data = buff.buffConfig.dataConfig.data
        if data.ContainsKey ~= nil and not data:ContainsKey("Id") then
            return nil
        end
        return data:get_Item("Id")
    end)
    if ok then
        return buffId
    end
    return nil
end

function SunExp_GetNegativeBuffSummary(target)
    local ids = {}
    local total = 0
    if target == nil then
        return ids, total
    end
    local ok, buffs = pcall(function()
        return target:GetBuffs()
    end)
    if not ok or buffs == nil then
        return ids, total
    end
    local count = SunExp_GetCollectionCount(buffs)
    for i = 0, count - 1 do
        local buff = SunExp_GetCollectionItem(buffs, i)
        if SunExp_IsNegativeBuffItem(buff) then
            local id = SunExp_GetBuffIdFromItem(buff)
            if id ~= nil then
                if buff.buffConfig ~= nil then
                    total = total + (tonumber(buff.buffConfig.Level) or 0)
                end
                table.insert(ids, id)
            end
        end
    end
    return ids, total
end

function SunExp_GetNegativeBuffTotal(target)
    local ids, total = SunExp_GetNegativeBuffSummary(target)
    return tonumber(total) or 0
end

function SunExp_RemoveAllNegativeBuffs(self, target)
    if self == nil then
        return false
    end
    local ids = SunExp_GetNegativeBuffSummary(target)
    for _, id in ipairs(ids) do
        SunExp_RemoveStatusBuff(self, target or self.Self, id)
    end
    return #ids > 0
end

function SunExp_HasNegativeBuff(target)
    if target == nil then
        return false
    end
    local ok, buffs = pcall(function()
        return target:GetBuffs()
    end)
    if not ok or buffs == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(buffs)
    for i = 0, count - 1 do
        if SunExp_IsNegativeBuffItem(SunExp_GetCollectionItem(buffs, i)) then
            return true
        end
    end
    return false
end
-- </module: combat/negative_buffs.lua>
end

do
-- <module: mechanics/radiance_crown_burn.lua>
function SunExp_HasCrownPhase(self, threshold)
    if self == nil or self.Self == nil then
        return false
    end
    local crown = self.Self:GetBuff("SunExp_sunexp_solar_crown")
    return crown ~= nil and SunExp_GetRadianceLevel(self) >= threshold
end

function SunExp_IsBurnWardPending(self)
    return SunExp_GetVar(self, "SunExpBurnWardPending", "0") == "1"
end

function SunExp_SetBurnWardPending(self, value)
    SunExp_SetVar(self, "SunExpBurnWardPending", value and "1" or "0")
end

function SunExp_IsSelfBurnProtected(self, includePending)
    if self == nil or self.Self == nil then
        return false
    end
    local ward = self.Self:GetBuff("SunExp_sunexp_ember_cloak")
    if ward ~= nil and ward.buffConfig ~= nil and ward.buffConfig.Level > 0 then
        return true
    end
    if includePending and SunExp_IsBurnWardPending(self) then
        return true
    end
    return SunExp_HasCrownPhase(self, 12)
end

function SunExp_ClearSelfBurnIfProtected(self, includePending)
    if self == nil or self.Self == nil then
        return false
    end
    if SunExp_IsSelfBurnProtected(self, includePending) then
        SunExp_RemoveStatusBuff(self, self.Self, "buff_burn")
        return true
    end
    return false
end

function SunExp_ApplySelfBurn(self, amount, includePending)
    if self == nil or amount == nil or amount <= 0 then
        return false
    end
    if SunExp_IsSelfBurnProtected(self, includePending) then
        if self.Self ~= nil then
            SunExp_RemoveStatusBuff(self, self.Self, "buff_burn")
        end
        return false
    end
    self:SetStatus("Self")
    self:AddBuff("buff_burn", tostring(amount))
    return true
end
-- </module: mechanics/radiance_crown_burn.lua>
end

do
-- <module: mechanics/hooks.lua>
function SunExp_RegisterHook(self, hookKey, tokenKey)
    if self == nil or self.Vars == nil then
        return "0"
    end
    if self.Vars:ContainsKey(hookKey) and self.Vars:get_Item(hookKey) == "1" then
        return nil
    end
    local token = tonumber(SunExp_GetVar(self, tokenKey, "0")) or 0
    token = token + 1
    self.Vars:set_Item(hookKey, "1")
    self.Vars:set_Item(tokenKey, tostring(token))
    return tostring(token)
end

function SunExp_IsHookTokenActive(self, tokenKey, token)
    if self == nil or self.Vars == nil then
        return true
    end
    return SunExp_GetVar(self, tokenKey, "") == tostring(token)
end

function SunExp_ClearHook(self, hookKey, tokenKey)
    if self == nil or self.Vars == nil then
        return
    end
    self.Vars:set_Item(hookKey, "0")
    local token = tonumber(SunExp_GetVar(self, tokenKey, "0")) or 0
    self.Vars:set_Item(tokenKey, tostring(token + 1))
end
-- </module: mechanics/hooks.lua>
end

do
-- <module: cards/flamewheel.lua>
function SunExp_FlamewheelKey()
    return "SunExp_flamewheel_recurrence_count"
end

function SunExp_GetFlamewheelSkillTime()
    local skillTime = nil
    pcall(function()
        if CS ~= nil and CS.ScriptExecutor ~= nil and CS.ScriptExecutor.PlayerInfo ~= nil then
            skillTime = CS.ScriptExecutor.PlayerInfo.SkillTime
        end
    end)
    return skillTime
end

function SunExp_GetFlamewheelUsed()
    local st = SunExp_GetFlamewheelSkillTime()
    if st == nil then
        return 0
    end
    local key = SunExp_FlamewheelKey()
    pcall(function()
        if st.ContainsKey ~= nil and not st:ContainsKey(key) then
            st:set_Item(key, 0)
        end
    end)
    local ok, value = pcall(function()
        return st:get_Item(key)
    end)
    if ok then
        return tonumber(value) or 0
    end
    return 0
end

function SunExp_SetFlamewheelUsed(value)
    local st = SunExp_GetFlamewheelSkillTime()
    if st == nil then
        return false
    end
    local ok = pcall(function()
        st:set_Item(SunExp_FlamewheelKey(), tonumber(value) or 0)
    end)
    return ok
end

function SunExp_SetFlamewheelCost(cardData, used)
    if cardData == nil then
        return false
    end
    local vars = nil
    pcall(function()
        vars = cardData.Vars
    end)
    if vars == nil then
        return false
    end
    local value = tostring(used or SunExp_GetFlamewheelUsed())
    local ok = pcall(function()
        vars:set_Item("ExCost", value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars["ExCost"] = value
    end)
    return ok
end

function SunExp_UpdateFlamewheelCost(cardData)
    return SunExp_SetFlamewheelCost(cardData)
end

function SunExp_IsFlamewheelCardItem(item)
    if item == nil then
        return false
    end
    local id = nil
    if item.data ~= nil and item.data.ContainsKey ~= nil and item.data:ContainsKey("Id") then
        id = item.data:get_Item("Id")
    end
    if id == nil and item.dataConfig ~= nil and item.dataConfig.data ~= nil and item.dataConfig.data.ContainsKey ~= nil and item.dataConfig.data:ContainsKey("Id") then
        id = item.dataConfig.data:get_Item("Id")
    end
    if id == nil then
        return false
    end
    return string.find(tostring(id), "flamewheel_recurrence", 1, true) ~= nil
end

function SunExp_TrySetFlamewheelItemCost(item, used)
    if item == nil then
        return false
    end
    local value = tostring(used)
    local changed = false
    pcall(function()
        if item.Vars ~= nil then
            item.Vars:set_Item("ExCost", value)
            changed = true
        end
    end)
    pcall(function()
        if item.dataConfig ~= nil and item.dataConfig.Vars ~= nil then
            item.dataConfig.Vars:set_Item("ExCost", value)
            changed = true
        end
    end)
    if changed then
        pcall(function()
            if item.DataUpdate ~= nil then
                item:DataUpdate()
            end
        end)
    end
    return changed
end

function SunExp_RefreshFlamewheelHand(self, used)
    if self == nil then
        return false
    end
    if SunExp_GetVar(self, "SunExpFlamewheelRefreshBusy", "0") == "1" then
        return false
    end
    SunExp_SetVar(self, "SunExpFlamewheelRefreshBusy", "1")
    local changed = false
    pcall(function()
        local hand = nil
        pcall(function()
            hand = self.HandCard
        end)
        if hand == nil then
            return
        end
        local nextCost = used
        if nextCost == nil then
            nextCost = SunExp_GetFlamewheelUsed()
        end
        local count = SunExp_GetCollectionCount(hand)
        for i = 0, count - 1 do
            local item = SunExp_GetCollectionItem(hand, i)
            if SunExp_IsFlamewheelCardItem(item) and SunExp_TrySetFlamewheelItemCost(item, nextCost) then
                changed = true
            end
        end
    end)
    SunExp_SetVar(self, "SunExpFlamewheelRefreshBusy", "0")
    return changed
end

function SunExp_RefreshFlamewheelCosts(self, used)
    return SunExp_RefreshFlamewheelHand(self, used)
end
-- </module: cards/flamewheel.lua>
end

do
-- <module: registry.lua>
function SunExp_RegisterDynamicMethod(config, name, fn)
    if config == nil or fn == nil then
        return
    end
    config:AddDynamicMethod(name, fn)
end

function SunExp_RegisterDynamicMethods(config)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerInfo", SunExp_PlayerInfo)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerGetVar", SunExp_PlayerGetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerSetVar", SunExp_PlayerSetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GainGold", SunExp_GainGold)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddCardReward", SunExp_AddCardReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddRelicReward", SunExp_AddRelicReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBlessReward", SunExp_AddBlessReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_EndEvent", SunExp_EndEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_ShowCaption", SunExp_ShowCaption)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaProgressKey", SunExp_WunaProgressKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetWunaProgress", SunExp_GetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetWunaProgress", SunExp_SetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaLevelKey", SunExp_WunaLevelKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapLevel", SunExp_GetCurrentMapLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapLevelNumber", SunExp_GetCurrentMapLevelNumber)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasWunaEventInCurrentLevel", SunExp_HasWunaEventInCurrentLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_MarkWunaEventInCurrentLevel", SunExp_MarkWunaEventInCurrentLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_AdvanceWunaEvent", SunExp_AdvanceWunaEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaFinish", SunExp_WunaFinish)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetEventChoiceVar", SunExp_TrySetEventChoiceVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetEventChoices", SunExp_SetEventChoices)
    SunExp_RegisterDynamicMethod(config, "SunExp_BeginWunaRepeatEvent", SunExp_BeginWunaRepeatEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_BeginWunaEvent", SunExp_BeginWunaEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardCard", SunExp_WunaRewardCard)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardRelic", SunExp_WunaRewardRelic)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardBless", SunExp_WunaRewardBless)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardNone", SunExp_WunaRewardNone)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRepeatReward", SunExp_WunaRepeatReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_SolarEventMapId", SunExp_SolarEventMapId)
    SunExp_RegisterDynamicMethod(config, "SunExp_SolarEventPlaceholderNodeId", SunExp_SolarEventPlaceholderNodeId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventMapId", SunExp_IsSolarEventMapId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventPlaceholderNodeId", SunExp_IsSolarEventPlaceholderNodeId)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentSolarEventId", SunExp_GetCurrentSolarEventId)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookField", SunExp_TryGetHookField)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookArguments", SunExp_TryGetHookArguments)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookTarget", SunExp_TryGetHookTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetNodeData", SunExp_TrySetNodeData)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetNodeDataValue", SunExp_TryGetNodeDataValue)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventNode", SunExp_IsSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsEventNode", SunExp_IsEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetMapTree", SunExp_GetMapTree)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapTree", SunExp_GetCurrentMapTree)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerSegmentSize", SunExp_GetSolarLayerSegmentSize)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerStartIndex", SunExp_GetSolarLayerStartIndex)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerRange", SunExp_GetSolarLayerRange)
    SunExp_RegisterDynamicMethod(config, "SunExp_CreateSolarEventNode", SunExp_CreateSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSelectNodes", SunExp_GetSelectNodes)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsBreakNode", SunExp_IsBreakNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsProtectedFixedEventNode", SunExp_IsProtectedFixedEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetSolarEventNode", SunExp_TrySetSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryReplaceNodeAt", SunExp_TryReplaceNodeAt)
    SunExp_RegisterDynamicMethod(config, "SunExp_EnsureSolarEventInCurrentLayer", SunExp_EnsureSolarEventInCurrentLayer)
    SunExp_RegisterDynamicMethod(config, "SunExp_EnsureSolarEventInCurrentLayerFromHook", SunExp_EnsureSolarEventInCurrentLayerFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventNode", SunExp_TryAppendSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventNodeFromHook", SunExp_TryAppendSolarEventNodeFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventNode", SunExp_TryRepairSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventNodes", SunExp_TryRepairSolarEventNodes)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventSyncedMapData", SunExp_TryRepairSolarEventSyncedMapData)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventSelectedNodesFromHook", SunExp_TryRepairSolarEventSelectedNodesFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetMapSelectSolarChoiceCounts", SunExp_GetMapSelectSolarChoiceCounts)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryCreateSolarEventChoiceUI", SunExp_TryCreateSolarEventChoiceUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventChoiceForUI", SunExp_TryAppendSolarEventChoiceForUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventChoiceUI", SunExp_TryAppendSolarEventChoiceUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventMapArrays", SunExp_TryRepairSolarEventMapArrays)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventMapSelection", SunExp_TryRepairSolarEventMapSelection)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventGeneratedMap", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetVar", SunExp_GetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetVar", SunExp_SetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffLevel", SunExp_GetBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRadianceLevel", SunExp_GetRadianceLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealDamage", SunExp_DealDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddDamageDescription", SunExp_AddDamageDescription)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSparkDamage", SunExp_CalcSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlareCutDamage", SunExp_CalcFlareCutDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarSparkDamage", SunExp_CalcSolarSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownPressureDamage", SunExp_CalcCrownPressureDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownCoreFlashDamage", SunExp_CalcCrownCoreFlashDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlamePierceDamage", SunExp_CalcFlamePierceDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSmokeErosionDamage", SunExp_CalcSmokeErosionDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetEnemyTargets", SunExp_GetEnemyTargets)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfStatus", SunExp_IsSelfStatus)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetPrimaryTarget", SunExp_GetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetPrimaryTarget", SunExp_SetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusForBuff", SunExp_SetStatusForBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuff", SunExp_GetStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuffLevel", SunExp_GetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveStatusBuff", SunExp_RemoveStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusBuffLevel", SunExp_SetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddStatusBuff", SunExp_AddStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerStatusBuff", SunExp_TriggerStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurn", SunExp_TriggerBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurnAllEnemies", SunExp_TriggerBurnAllEnemies)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRandomEnemyTarget", SunExp_GetRandomEnemyTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBurnToRandomEnemy", SunExp_AddBurnToRandomEnemy)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveBuffStacks", SunExp_RemoveBuffStacks)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionCount", SunExp_GetCollectionCount)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionItem", SunExp_GetCollectionItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetCollectionItem", SunExp_TrySetCollectionItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffTypeName", SunExp_GetBuffTypeName)
    SunExp_RegisterDynamicMethod(config, "SunExp_NormalizeBuffId", SunExp_NormalizeBuffId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedId", SunExp_IsPositiveBuffExcludedId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedItem", SunExp_IsPositiveBuffExcludedItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsNegativeBuffItem", SunExp_IsNegativeBuffItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffIdFromItem", SunExp_GetBuffIdFromItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffSummary", SunExp_GetNegativeBuffSummary)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffTotal", SunExp_GetNegativeBuffTotal)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveAllNegativeBuffs", SunExp_RemoveAllNegativeBuffs)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasNegativeBuff", SunExp_HasNegativeBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasCrownPhase", SunExp_HasCrownPhase)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsBurnWardPending", SunExp_IsBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetBurnWardPending", SunExp_SetBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfBurnProtected", SunExp_IsSelfBurnProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearSelfBurnIfProtected", SunExp_ClearSelfBurnIfProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplySelfBurn", SunExp_ApplySelfBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_RegisterHook", SunExp_RegisterHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsHookTokenActive", SunExp_IsHookTokenActive)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearHook", SunExp_ClearHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_FlamewheelKey", SunExp_FlamewheelKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetFlamewheelSkillTime", SunExp_GetFlamewheelSkillTime)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetFlamewheelUsed", SunExp_GetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetFlamewheelUsed", SunExp_SetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetFlamewheelCost", SunExp_SetFlamewheelCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_UpdateFlamewheelCost", SunExp_UpdateFlamewheelCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsFlamewheelCardItem", SunExp_IsFlamewheelCardItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetFlamewheelItemCost", SunExp_TrySetFlamewheelItemCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_RefreshFlamewheelHand", SunExp_RefreshFlamewheelHand)
    SunExp_RegisterDynamicMethod(config, "SunExp_RefreshFlamewheelCosts", SunExp_RefreshFlamewheelCosts)
end
-- </module: registry.lua>
end

do
-- <module: setup.lua>
function SunExp_TryAddMethodHookBefore(config, typeDotMethod, fn)
    if config == nil or typeDotMethod == nil or fn == nil then
        return false
    end
    local ok = pcall(function()
        config:AddMethodHookBefore(typeDotMethod, fn)
    end)
    return ok
end

function SunExp_TryAddMethodHookAfter(config, typeDotMethod, fn)
    if config == nil or typeDotMethod == nil or fn == nil then
        return false
    end
    local ok = pcall(function()
        config:AddMethodHookAfter(typeDotMethod, fn)
    end)
    return ok
end

function ModConfig:Setup()
    SunExp_RegisterDynamicMethods(self)
    SunExp_TryAddMethodHookBefore(self, "MapSelectUI.ReadyToSelect", SunExp_EnsureSolarEventInCurrentLayerFromHook)
    SunExp_TryAddMethodHookAfter(self, "NormalMapManager.RandomGenerate", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_TryAddMethodHookAfter(self, "NormalMapManager.GeneratrMap", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_TryAddMethodHookBefore(self, "MapManager.UserCode_CmdSelectMap__String[]__String[]__NetworkConnectionToClient", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.UserCode_CmdSelectMapIncludeSender__String[]__String[]__NetworkConnectionToClient", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.CmdSelectMap", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.CmdSelectMapIncludeSender", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.TargetUpdateMap", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.RpcUpdateMap", SunExp_TryRepairSolarEventMapSelection)
end
-- </module: setup.lua>
end
