-- Generated by tools/Build-SunExpEntry.ps1 from SunExp/Scripts/_src.
-- Edit the _src modules, then rebuild this file.
-- The game runtime only guarantees Scripts/Entry.lua as the mod load entry.

do
-- <module: core/vars.lua>
function SunExp_GetVar(self, key, defaultValue)
    if self == nil or self.Vars == nil or not self.Vars:ContainsKey(key) then
        return defaultValue
    end
    return self.Vars:get_Item(key)
end

function SunExp_SetVar(self, key, value)
    if self == nil or self.Vars == nil then
        return
    end
    self.Vars:set_Item(key, tostring(value))
end
-- </module: core/vars.lua>
end

do
-- <module: core/player.lua>
function SunExp_PlayerInfo()
    if CS == nil or CS.ScriptExecutor == nil then
        return nil
    end
    return CS.ScriptExecutor.PlayerInfo
end

function SunExp_PlayerGetVar(key, defaultValue)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return defaultValue
    end
    local ok, value = pcall(function()
        return player.GetGameVar(key)
    end)
    if ok and value ~= nil and tostring(value) ~= "" then
        return tostring(value)
    end
    return defaultValue
end

function SunExp_PlayerSetVar(key, value)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local ok = pcall(function()
        player.SetGameVar(key, tostring(value))
    end)
    return ok
end

function SunExp_GainGold(amount)
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local value = math.floor(tonumber(amount) or 0)
    if value == 0 then
        return true
    end
    local ok = pcall(function()
        player.Money = (tonumber(player.Money) or 0) + value
    end)
    return ok
end

function SunExp_AddCardReward(cardId)
    local player = SunExp_PlayerInfo()
    if player == nil or cardId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddCard(cardId)
    end)
    return ok
end

function SunExp_AddRelicReward(relicId)
    local player = SunExp_PlayerInfo()
    if player == nil or relicId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddRelic(relicId)
    end)
    return ok
end

function SunExp_AddBlessReward(blessId)
    local player = SunExp_PlayerInfo()
    if player == nil or blessId == nil then
        return false
    end
    local ok = pcall(function()
        player.AddBless(blessId)
    end)
    return ok
end

function SunExp_EndEvent()
    local player = SunExp_PlayerInfo()
    if player == nil then
        return false
    end
    local ok = pcall(function()
        player.EndEvent()
    end)
    return ok
end

function SunExp_ShowCaption(text)
    local player = SunExp_PlayerInfo()
    if player == nil or text == nil then
        return false
    end
    local ok = pcall(function()
        player.ShowCaption(text)
    end)
    return ok
end
-- </module: core/player.lua>
end

do
-- <module: events/wuna_solar_event.lua>
function SunExp_WunaProgressKey()
    return "SunExp_WunaEventProgressV2"
end

function SunExp_GetWunaProgress()
    return tonumber(SunExp_PlayerGetVar(SunExp_WunaProgressKey(), "0")) or 0
end

function SunExp_SetWunaProgress(progress)
    return SunExp_PlayerSetVar(SunExp_WunaProgressKey(), tostring(progress))
end

function SunExp_WunaLevelKey()
    return "SunExp_WunaEventLevelV2"
end

function SunExp_GetCurrentMapLevel()
    local level = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            level = CS.MapManager.Instance.Level
        end
    end)
    return tostring(level or "unknown")
end

function SunExp_GetCurrentMapLevelNumber()
    local level = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            level = CS.MapManager.Instance.Level
        end
    end)
    if level == nil then
        pcall(function()
            if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil and CS.MapManager.Instance.ModeMapManager ~= nil then
                level = CS.MapManager.Instance.ModeMapManager.Level
            end
        end)
    end
    return tonumber(level) or 0
end

function SunExp_HasWunaEventInCurrentLevel()
    return false
end

function SunExp_MarkWunaEventInCurrentLevel()
    return true
end

function SunExp_AdvanceWunaEvent(progress)
    local current = SunExp_GetWunaProgress()
    local nextProgress = math.max(current, tonumber(progress) or current)
    SunExp_SetWunaProgress(nextProgress)
end

function SunExp_WunaFinish(progress)
    SunExp_AdvanceWunaEvent(progress)
    SunExp_EndEvent()
end

function SunExp_TrySetEventChoiceVar(vars, key, value)
    if vars == nil or key == nil then
        return false
    end
    local text = tostring(value)
    local ok = pcall(function()
        vars:set_Item(key, text)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars[key] = text
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars:Set(key, text)
    end)
    return ok
end

function SunExp_SetEventChoices(executor, choice1, choice2, choice3, choice4)
    local vars = nil
    if executor ~= nil then
        pcall(function()
            vars = executor.Vars
        end)
    end
    if vars == nil then
        pcall(function()
            if Vars ~= nil then
                vars = Vars
            end
        end)
    end
    if vars == nil then
        return false
    end
    local choices = { choice1, choice2, choice3, choice4 }
    local changed = false
    for i = 1, 4 do
        local value = "0"
        if choices[i] ~= nil and tostring(choices[i]) ~= "" then
            value = choices[i]
        end
        changed = SunExp_TrySetEventChoiceVar(vars, "Choice" .. tostring(i), value) or changed
    end
    return changed
end

function SunExp_BeginWunaRepeatEvent(executor)
    return SunExp_SetEventChoices(executor, "1")
end

function SunExp_BeginWunaEvent(executor, step)
    local expected = math.max(1, math.min(6, tonumber(step) or 1))
    local current = SunExp_GetWunaProgress()
    if current ~= expected - 1 then
        return SunExp_BeginWunaRepeatEvent(executor)
    end
    return SunExp_SetEventChoices(executor, "1", "1")
end

function SunExp_WunaRewardCard(progress, cardId)
    SunExp_GainGold(100)
    SunExp_AddCardReward(cardId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardRelic(progress, relicId)
    SunExp_GainGold(100)
    SunExp_AddRelicReward(relicId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardBless(progress, blessId)
    SunExp_GainGold(100)
    SunExp_AddBlessReward(blessId)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRewardNone(progress)
    SunExp_GainGold(100)
    SunExp_WunaFinish(progress)
end

function SunExp_WunaRepeatReward()
    SunExp_AddBlessReward("blessing_8")
    SunExp_EndEvent()
end

function SunExp_SolarEventMapId()
    return "SunExp_sunexp_solar_event"
end

function SunExp_SolarEventPlaceholderNodeId()
    return "SunExp_sunexp_solar_event"
end

function SunExp_IsSolarEventMapId(id)
    if id == nil then
        return false
    end
    local value = tostring(id)
    return value == "SunExp_sunexp_solar_event" or value == "solar_event"
end

function SunExp_IsSolarEventPlaceholderNodeId(id)
    return SunExp_IsSolarEventMapId(id)
end

function SunExp_GetCurrentSolarEventId()
    if SunExp_GetWunaProgress() >= 6 then
        return "SunExp_sunexp_Sub_wuna_event_repeat"
    end
    local nextEvent = math.min(6, math.max(1, SunExp_GetWunaProgress() + 1))
    return string.format("SunExp_sunexp_Sub_wuna_event_%02d", nextEvent)
end

function SunExp_TryGetHookField(obj, fieldName)
    if obj == nil or fieldName == nil then
        return nil
    end
    local ok, value = pcall(function()
        return obj[fieldName]
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return obj:get_Item(fieldName)
    end)
    if ok and value ~= nil then
        return value
    end
    return nil
end

function SunExp_TryGetHookArguments(obj)
    return SunExp_TryGetHookField(obj, "Arguments")
end

function SunExp_TryGetHookTarget(obj)
    return SunExp_TryGetHookField(obj, "Target")
end

function SunExp_TrySetNodeData(node, key, value)
    if node == nil or node.data == nil or key == nil then
        return false
    end
    local text = tostring(value)
    local ok = pcall(function()
        node.data:set_Item(key, text)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        node.data[key] = text
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        node.data:Set(key, text)
    end)
    return ok
end

function SunExp_TryGetNodeDataValue(node, key)
    if node == nil or node.data == nil or key == nil then
        return nil
    end
    local ok, value = pcall(function()
        if node.data.ContainsKey ~= nil and not node.data:ContainsKey(key) then
            return nil
        end
        return node.data:get_Item(key)
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return node.data[key]
    end)
    if ok then
        return value
    end
    return nil
end

function SunExp_IsSolarEventNode(node)
    return SunExp_IsSolarEventMapId(SunExp_TryGetNodeDataValue(node, "Id"))
end

function SunExp_IsEventNode(node)
    local typeName = SunExp_TryGetNodeDataValue(node, "Type")
    if typeName ~= nil and tostring(typeName) == "Event" then
        return true
    end
    local nodeType = nil
    pcall(function()
        nodeType = node.type
    end)
    return tostring(nodeType or "") == "Event"
end

function SunExp_GetMapTree(treeOrManager)
    if treeOrManager == nil then
        return nil
    end
    local tree = nil
    pcall(function()
        tree = treeOrManager.MapTree
    end)
    if tree ~= nil then
        return tree
    end
    pcall(function()
        tree = treeOrManager.mapTree
    end)
    if tree ~= nil then
        return tree
    end
    return treeOrManager
end

function SunExp_GetCurrentMapTree()
    local tree = nil
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil then
            tree = CS.MapManager.Instance.MapTree
        end
    end)
    if tree ~= nil then
        return tree
    end
    pcall(function()
        if CS ~= nil and CS.MapManager ~= nil and CS.MapManager.Instance ~= nil and CS.MapManager.Instance.ModeMapManager ~= nil then
            tree = CS.MapManager.Instance.ModeMapManager.MapTree
        end
    end)
    return tree
end

function SunExp_GetSolarLayerSegmentSize()
    local exDelete = 0
    if SunExp_TestExDeleteDes ~= nil then
        exDelete = tonumber(SunExp_TestExDeleteDes) or 0
    else
        pcall(function()
            if CS ~= nil and CS.GameSaveManager ~= nil and CS.GameVar ~= nil then
                exDelete = tonumber(CS.GameSaveManager.GetValue(CS.GameVar.ExDeleteDes)) or exDelete
            end
        end)
        pcall(function()
            if CS ~= nil and CS.GameSaveManager ~= nil then
                exDelete = tonumber(CS.GameSaveManager.GetValue("ExDeleteDes")) or exDelete
            end
        end)
    end
    local size = 8 - exDelete
    if size < 1 then
        return 1
    end
    return size
end

function SunExp_GetSolarLayerStartIndex()
    local level = SunExp_GetCurrentMapLevelNumber()
    return math.floor(level / 6) * SunExp_GetSolarLayerSegmentSize()
end

function SunExp_GetSolarLayerRange()
    return SunExp_GetSolarLayerStartIndex(), SunExp_GetSolarLayerSegmentSize()
end

function SunExp_CreateSolarEventNode(treeOrManager)
    local tree = SunExp_GetMapTree(treeOrManager)
    if tree == nil then
        tree = SunExp_GetCurrentMapTree()
    end
    local node = nil
    pcall(function()
        if tree ~= nil and tree.GetNodeByNodeId ~= nil then
            node = tree:GetNodeByNodeId(SunExp_SolarEventPlaceholderNodeId())
        end
    end)
    if node == nil then
        pcall(function()
            node = CS.MapTree.Node.New("Event")
        end)
    end
    if node == nil then
        return nil
    end
    if node.data == nil then
        return nil
    end
    pcall(function()
        node.type = "Event"
    end)
    SunExp_TrySetNodeData(node, "Id", SunExp_SolarEventMapId())
    SunExp_TrySetNodeData(node, "Type", "Event")
    SunExp_TrySetNodeData(node, "NodeId", SunExp_GetCurrentSolarEventId())
    SunExp_TrySetNodeData(node, "Level", "-1")
    return node
end

function SunExp_GetSelectNodes(treeOrManager)
    local tree = SunExp_GetMapTree(treeOrManager)
    if tree == nil then
        tree = SunExp_GetCurrentMapTree()
    end
    local nodes = nil
    pcall(function()
        if tree ~= nil then
            nodes = tree.SelectNode
        end
    end)
    return nodes
end

function SunExp_IsBreakNode(node)
    local nodeId = SunExp_TryGetNodeDataValue(node, "NodeId")
    if nodeId ~= nil and string.find(tostring(nodeId), "Breaks", 1, true) ~= nil then
        return true
    end
    local id = SunExp_TryGetNodeDataValue(node, "Id")
    if id ~= nil and string.find(tostring(id), "Breaks", 1, true) ~= nil then
        return true
    end
    return false
end

function SunExp_IsProtectedFixedEventNode(node)
    local nodeId = SunExp_TryGetNodeDataValue(node, "NodeId")
    if nodeId == nil then
        return false
    end
    local value = tostring(nodeId)
    return value == "event_2001"
        or value == "event_2002"
        or value == "event_2003"
        or value == "event_2004"
        or value == "event_2005"
        or value == "event_2006"
        or value == "event_2015"
        or value == "event_999"
end

function SunExp_TrySetSolarEventNode(node)
    if node == nil or node.data == nil then
        return false
    end
    local changed = false
    changed = SunExp_TrySetNodeData(node, "Id", SunExp_SolarEventMapId()) or changed
    changed = SunExp_TrySetNodeData(node, "Type", "Event") or changed
    changed = SunExp_TrySetNodeData(node, "NodeId", SunExp_GetCurrentSolarEventId()) or changed
    changed = SunExp_TrySetNodeData(node, "Level", "-1") or changed
    pcall(function()
        node.type = "Event"
    end)
    return changed
end

function SunExp_TryReplaceNodeAt(collection, index, replacement)
    if SunExp_TrySetCollectionItem(collection, index, replacement) then
        return true
    end
    return false
end

function SunExp_EnsureSolarEventInCurrentLayer(treeOrManager)
    local nodes = SunExp_GetSelectNodes(treeOrManager)
    if nodes == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    if count <= 0 then
        return false
    end
    local startIndex, segmentSize = SunExp_GetSolarLayerRange()
    if startIndex >= count then
        return false
    end
    local endIndex = math.min(count - 1, startIndex + segmentSize - 1)
    local firstEventIndex = nil
    local firstFallbackIndex = nil
    for i = startIndex, endIndex do
        local node = SunExp_GetCollectionItem(nodes, i)
        if SunExp_IsSolarEventNode(node) then
            return SunExp_TrySetSolarEventNode(node)
        end
        if node ~= nil and not SunExp_IsBreakNode(node) and not SunExp_IsProtectedFixedEventNode(node) then
            if firstFallbackIndex == nil then
                firstFallbackIndex = i
            end
            if firstEventIndex == nil and SunExp_IsEventNode(node) then
                firstEventIndex = i
            end
        end
    end
    local replaceIndex = firstEventIndex or firstFallbackIndex
    if replaceIndex == nil then
        return false
    end
    local node = SunExp_CreateSolarEventNode(treeOrManager)
    if node == nil then
        node = SunExp_GetCollectionItem(nodes, replaceIndex)
        if not SunExp_TrySetSolarEventNode(node) then
            return false
        end
        return true
    end
    if SunExp_TryReplaceNodeAt(nodes, replaceIndex, node) then
        return true
    end
    return SunExp_TrySetSolarEventNode(SunExp_GetCollectionItem(nodes, replaceIndex))
end

function SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local target = SunExp_TryGetHookTarget(context)
            if target == nil then
                target = context
            end
            if SunExp_EnsureSolarEventInCurrentLayer(target) then
                changed = true
            end
        end
    end)
    return changed
end

function SunExp_TryAddCollectionItem(collection, value)
    if collection == nil or value == nil then
        return false
    end
    local ok = pcall(function()
        collection:Add(value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        table.insert(collection, value)
    end)
    return ok
end

function SunExp_TryReplaceFirstEventNode(nodes, replacement)
    if nodes == nil or replacement == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        local node = SunExp_GetCollectionItem(nodes, i)
        if SunExp_IsEventNode(node) then
            return SunExp_TrySetCollectionItem(nodes, i, replacement)
        end
    end
    return false
end

function SunExp_TryAppendSolarEventNode(nodes, treeOrManager)
    if nodes == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        if SunExp_IsSolarEventNode(SunExp_GetCollectionItem(nodes, i)) then
            return false
        end
    end
    local node = SunExp_CreateSolarEventNode(treeOrManager)
    if node == nil then
        return false
    end
    if SunExp_TryAddCollectionItem(nodes, node) then
        return true
    end
    return SunExp_TryReplaceFirstEventNode(nodes, node)
end

function SunExp_TryAppendSolarEventNodeFromHook(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local target = SunExp_TryGetHookTarget(context)
            local hookArgs = SunExp_TryGetHookArguments(context)
            local count = SunExp_GetCollectionCount(hookArgs)
            for j = 0, count - 1 do
                if SunExp_TryAppendSolarEventNode(SunExp_GetCollectionItem(hookArgs, j), target) then
                    changed = true
                    return
                end
            end
            if hookArgs == nil and SunExp_TryAppendSolarEventNode(context, target) then
                changed = true
                return
            end
        end
    end)
    return changed
end

function SunExp_TryRepairSolarEventNode(node)
    if SunExp_IsSolarEventNode(node) then
        return SunExp_TrySetSolarEventNode(node)
    end
    return false
end

function SunExp_TryRepairSolarEventNodes(nodes)
    if nodes == nil then
        return false
    end
    local changed = false
    local count = SunExp_GetCollectionCount(nodes)
    for i = 0, count - 1 do
        changed = SunExp_TryRepairSolarEventNode(SunExp_GetCollectionItem(nodes, i)) or changed
    end
    return changed
end

function SunExp_TryRepairSolarEventSyncedMapData()
    return false
end

function SunExp_TryRepairSolarEventSelectedNodesFromHook(...)
    return SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
end

function SunExp_TryRepairSolarEventGeneratedMap(...)
    return SunExp_EnsureSolarEventInCurrentLayerFromHook(...)
end

function SunExp_GetMapSelectSolarChoiceCounts(ui)
    return 0, 0
end

function SunExp_TryCreateSolarEventChoiceUI(ui)
    return false
end

function SunExp_TryAppendSolarEventChoiceForUI(ui)
    return false
end

function SunExp_TryAppendSolarEventChoiceUI(...)
    return false
end

function SunExp_TryRepairSolarEventMapArrays(maps, mapdata)
    if maps == nil or mapdata == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(maps)
    if count <= 0 then
        return false
    end
    local changed = false
    for i = 0, count - 1 do
        local mapId = SunExp_GetCollectionItem(maps, i)
        if SunExp_IsSolarEventMapId(mapId) then
            SunExp_TrySetCollectionItem(maps, i, SunExp_SolarEventMapId())
            changed = SunExp_TrySetCollectionItem(mapdata, i, SunExp_GetCurrentSolarEventId()) or changed
        end
    end
    return changed
end

function SunExp_TryRepairSolarEventMapSelection(...)
    local args = {...}
    local changed = false
    pcall(function()
        for i = 1, #args do
            local context = args[i]
            local hookArgs = SunExp_TryGetHookArguments(context)
            if hookArgs == nil then
                hookArgs = context
            end
            local count = SunExp_GetCollectionCount(hookArgs)
            for j = 0, count - 2 do
                local maps = SunExp_GetCollectionItem(hookArgs, j)
                local mapdata = SunExp_GetCollectionItem(hookArgs, j + 1)
                if SunExp_TryRepairSolarEventMapArrays(maps, mapdata) then
                    changed = true
                end
            end
        end
    end)
    return changed
end

function SunExp_TryRepairSolarEventLoadArgumentList(arguments)
    return false
end

function SunExp_TryRepairSolarEventLoad(...)
    return false
end
-- </module: events/wuna_solar_event.lua>
end

do
-- <module: combat/damage.lua>
function SunExp_GetBuffLevel(self, buffId)
    if self == nil or self.Self == nil then
        return 0
    end
    local buff = self.Self:GetBuff(buffId)
    if buff == nil or buff.buffConfig == nil or buff.buffConfig.Level == nil then
        return 0
    end
    return tonumber(buff.buffConfig.Level) or buff.buffConfig.Level or 0
end

function SunExp_GetRadianceLevel(self)
    return SunExp_GetBuffLevel(self, "SunExp_sunexp_solar_radiance")
end

function SunExp_GetSolarMultiplier(self)
    if self ~= nil and self.Self ~= nil and self.Self:GetBuff("SunExp_sunexp_solar_crown") ~= nil then
        return 2
    end
    return 1
end

function SunExp_CalcSolarCoefficient(self, target)
    local radiance = SunExp_GetRadianceLevel(self)
    local flame = SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame")
    local burn = SunExp_GetStatusBuffLevel(target, "buff_burn")
    return SunExp_GetSolarMultiplier(self) * (radiance * 2 + math.floor(flame / 3) + math.floor(burn / 2))
end

function SunExp_DealDamage(self, amount)
    if self == nil then
        return false
    end
    local damage = math.floor(tonumber(amount) or 0)
    if damage <= 0 then
        return false
    end
    damage = SunExp_ApplyWunaEmberDamageBonus(self, damage)
    self:Damage(tostring(damage))
    return true
end

function SunExp_AddDamageDescription(self, index, amount)
    if self == nil then
        return 0
    end
    local damage = math.floor(tonumber(amount) or 0)
    if damage < 0 then
        damage = 0
    end
    pcall(function()
        self:AddDescription(tostring(index), "Damage", tostring(damage))
    end)
    return damage
end

function SunExp_CalcSolarKeywordDamage(self, base, target, coefficientScale)
    local scale = tonumber(coefficientScale) or 1
    return math.floor((tonumber(base) or 0) + SunExp_CalcSolarCoefficient(self, target) * scale)
end

function SunExp_CalcSolarKeywordBlock(self, base)
    return math.floor((tonumber(base) or 0) + SunExp_CalcSolarCoefficient(self, nil))
end

function SunExp_DealSolarKeywordDamage(self, base, target, fallbackStatus, coefficientScale)
    if target ~= nil then
        SunExp_SetStatusForBuff(self, target, fallbackStatus or "Target")
    elseif fallbackStatus ~= nil then
        self:SetStatus(fallbackStatus)
    end
    return SunExp_DealDamage(self, SunExp_CalcSolarKeywordDamage(self, base, target, coefficientScale))
end

function SunExp_DealSolarKeywordDamageAllEnemies(self, base, coefficientScale)
    local targets = SunExp_GetEnemyTargets(self)
    local maxDamage = 0
    for i = 1, #targets do
        local target = targets[i]
        local damage = SunExp_CalcSolarKeywordDamage(self, base, target, coefficientScale)
        if damage > maxDamage then
            maxDamage = damage
        end
        SunExp_SetPrimaryTarget(self, target)
        SunExp_DealDamage(self, damage)
    end
    return maxDamage
end

function SunExp_ApplySolarKeywordSkill(self, baseBlock)
    local block = SunExp_CalcSolarKeywordBlock(self, baseBlock)
    if block > 0 then
        self:SetStatus("Self")
        self:ChangeDefence(tostring(block))
    end
    return block
end

function SunExp_CalcSparkDamage(self)
    return 5
end

function SunExp_CalcFlareCutDamage(self)
    return 10
end

function SunExp_CalcFlareCutBonusDamage(self)
    return SunExp_CalcSolarKeywordBonusDamage(self, SunExp_GetPrimaryTarget(self))
end

function SunExp_CalcSolarSparkBaseDamage(self)
    local useFlame = math.min(5, SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame"))
    return 8 + useFlame * 2
end

function SunExp_CalcSolarSparkDamage(self)
    return SunExp_CalcSolarSparkBaseDamage(self)
end

function SunExp_CalcSolarSparkBonusDamage(self)
    return SunExp_CalcSolarKeywordBonusDamage(self, SunExp_GetPrimaryTarget(self))
end

function SunExp_CalcCrownPressureDamage(self)
    return 0
end

function SunExp_CalcCrownCoreFlashDamage(self)
    return SunExp_CalcSolarKeywordDamage(self, 40, SunExp_GetPrimaryTarget(self), 3)
end

function SunExp_CalcFlamePierceDamage(self)
    local target = SunExp_GetPrimaryTarget(self)
    local burnLevel = SunExp_GetStatusBuffLevel(target, "buff_burn")
    local flameLevel = SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame")
    local mult = math.max(1, math.floor(flameLevel / 4))
    return 8 + burnLevel * mult
end

function SunExp_CalcSmokeErosionDamage(self)
    local target = SunExp_GetPrimaryTarget(self)
    return 7 + SunExp_GetStatusBuffLevel(target, "buff_burn")
end
-- </module: combat/damage.lua>
end

do
-- <module: combat/targeting.lua>
function SunExp_GetEnemyTargets(self)
    local targets = {}
    if self == nil then
        return targets
    end
    pcall(function()
        self:SetStatus("AllTarget")
    end)
    if self.Object == nil then
        return targets
    end
    local count = SunExp_GetCollectionCount(self.Object)
    for i = 0, count - 1 do
        local target = SunExp_GetCollectionItem(self.Object, i)
        if target ~= nil and not SunExp_IsSelfStatus(self, target) then
            table.insert(targets, target)
        end
    end
    return targets
end

function SunExp_IsSelfStatus(self, target)
    return self ~= nil and self.Self ~= nil and target ~= nil and target.InstanceId ~= nil and self.Self.InstanceId == target.InstanceId
end

function SunExp_GetPrimaryTarget(self)
    if self == nil then
        return nil
    end
    if self.Target ~= nil and not SunExp_IsSelfStatus(self, self.Target) then
        return self.Target
    end
    pcall(function()
        self:SetStatus("Target")
    end)
    if self.Object == nil or self.Object.Count == nil or self.Object.Count <= 0 then
        return nil
    end
    local ok, target = pcall(function()
        return self.Object:get_Item(0)
    end)
    if ok and target ~= nil and not SunExp_IsSelfStatus(self, target) then
        return target
    end
    return nil
end

function SunExp_SetPrimaryTarget(self, target)
    if self == nil or target == nil then
        return false
    end
    if target.InstanceId ~= nil then
        local ok = pcall(function()
            self:SetStatusById(target.InstanceId)
        end)
        if ok then
            return true
        end
    end
    pcall(function()
        self:SetStatus("Target")
    end)
    return false
end

function SunExp_SetStatusForBuff(self, target, fallbackStatus)
    if self == nil then
        return false
    end
    if target ~= nil then
        if SunExp_IsSelfStatus(self, target) then
            self:SetStatus("Self")
            return true
        end
        return SunExp_SetPrimaryTarget(self, target)
    end
    if fallbackStatus ~= nil then
        self:SetStatus(fallbackStatus)
        return true
    end
    return false
end

function SunExp_GetStatusBuff(target, buffId)
    if target == nil or buffId == nil then
        return nil
    end
    local ok, buff = pcall(function()
        return target:GetBuff(buffId)
    end)
    if ok then
        return buff
    end
    return nil
end

function SunExp_GetStatusBuffLevel(target, buffId)
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil or buff.buffConfig.Level == nil then
        return 0
    end
    return tonumber(buff.buffConfig.Level) or 0
end

function SunExp_RemoveStatusBuff(self, target, buffId, fallbackStatus)
    if self == nil or buffId == nil then
        return false
    end
    SunExp_SetStatusForBuff(self, target, fallbackStatus)
    local ok = pcall(function()
        self:RemoveBuff(buffId)
    end)
    if ok then
        return true
    end
    if target ~= nil then
        ok = pcall(function()
            target:RemoveBuff(buffId)
        end)
        return ok
    end
    return false
end

function SunExp_SetStatusBuffLevel(self, target, buffId, level)
    local nextLevel = tonumber(level) or 0
    if target == nil or buffId == nil then
        return false
    end
    if nextLevel <= 0 then
        return SunExp_RemoveStatusBuff(self, target, buffId)
    end
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil then
        return false
    end
    buff.buffConfig.Level = nextLevel
    return true
end

function SunExp_AddStatusBuff(self, target, buffId, amount, fallbackStatus)
    if self == nil or buffId == nil or amount == nil then
        return false
    end
    local before = SunExp_GetStatusBuffLevel(target, buffId)
    if not SunExp_SetStatusForBuff(self, target, fallbackStatus) then
        return false
    end
    local ok = pcall(function()
        self:AddBuff(buffId, tostring(amount))
    end)
    if target == nil then
        return ok
    end
    local after = SunExp_GetStatusBuffLevel(target, buffId)
    if after > before then
        return true
    end
    ok = pcall(function()
        target:AddBuff(buffId, tonumber(amount) or amount)
    end)
    after = SunExp_GetStatusBuffLevel(target, buffId)
    if ok and after > before then
        return true
    end
    ok = pcall(function()
        target:AddBuff(buffId, tostring(amount))
    end)
    return ok and SunExp_GetStatusBuffLevel(target, buffId) > before
end

function SunExp_TriggerStatusBuff(self, target, buffId, eventName, fallbackStatus)
    if self == nil or buffId == nil then
        return false
    end
    if target ~= nil and SunExp_GetStatusBuffLevel(target, buffId) <= 0 then
        return false
    end
    if not SunExp_SetStatusForBuff(self, target, fallbackStatus) then
        return false
    end
    local ok = pcall(function()
        self:RunImmediately(buffId, eventName or "StartRound")
    end)
    return ok
end

function SunExp_TriggerBurn(self, target, fallbackStatus)
    return SunExp_TriggerStatusBuff(self, target, "buff_burn", "StartRound", fallbackStatus)
end

function SunExp_TriggerBurnAllEnemies(self, times)
    if self == nil then
        return 0
    end
    local count = tonumber(times) or 1
    if count < 1 then
        count = 1
    end
    local triggered = 0
    for n = 1, count do
        self:SetStatus("AllTarget")
        local ok = pcall(function()
            self:RunImmediately("buff_burn", "StartRound")
        end)
        if ok then
            triggered = triggered + 1
        end
    end
    return triggered
end

function SunExp_GetRandomEnemyTarget(self, requireBurn)
    local targets = SunExp_GetEnemyTargets(self)
    local candidates = {}
    for i = 1, #targets do
        local target = targets[i]
        if not requireBurn or SunExp_GetStatusBuffLevel(target, "buff_burn") > 0 then
            table.insert(candidates, target)
        end
    end
    if #candidates == 0 then
        return nil
    end
    return candidates[math.random(1, #candidates)]
end

function SunExp_AddBurnToRandomEnemy(self, amount)
    local target = SunExp_GetRandomEnemyTarget(self, false)
    if target == nil then
        return false
    end
    return SunExp_AddStatusBuff(self, target, "buff_burn", amount)
end

function SunExp_RemoveBuffStacks(selfOrTarget, targetOrBuffId, buffIdOrAmount, amountOrNil)
    local executor = nil
    local target = selfOrTarget
    local buffId = targetOrBuffId
    local amount = buffIdOrAmount
    if amountOrNil ~= nil then
        executor = selfOrTarget
        target = targetOrBuffId
        buffId = buffIdOrAmount
        amount = amountOrNil
    end
    local count = tonumber(amount) or 0
    if target == nil or buffId == nil or count <= 0 then
        return 0
    end
    local buff = SunExp_GetStatusBuff(target, buffId)
    if buff == nil or buff.buffConfig == nil then
        return 0
    end
    local level = tonumber(buff.buffConfig.Level) or 0
    local removed = math.min(level, count)
    if removed <= 0 then
        return 0
    end
    local nextLevel = level - removed
    if nextLevel <= 0 then
        if executor ~= nil then
            SunExp_RemoveStatusBuff(executor, target, buffId)
        else
            pcall(function()
                target:RemoveBuff(buffId)
            end)
        end
    else
        buff.buffConfig.Level = nextLevel
    end
    return removed
end
-- </module: combat/targeting.lua>
end

do
-- <module: core/collections.lua>
function SunExp_GetCollectionCount(collection)
    if collection == nil then
        return 0
    end
    local ok, count = pcall(function()
        return collection.Count
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return collection:Count()
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return collection.Length
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    ok, count = pcall(function()
        return #collection
    end)
    if ok and count ~= nil then
        return tonumber(count) or 0
    end
    return 0
end

function SunExp_GetCollectionItem(collection, index)
    if collection == nil then
        return nil
    end
    local ok, item = pcall(function()
        return collection:get_Item(index)
    end)
    if ok and item ~= nil then
        return item
    end
    ok, item = pcall(function()
        return collection[index]
    end)
    if ok and item ~= nil then
        return item
    end
    ok, item = pcall(function()
        return collection[index + 1]
    end)
    if ok and item ~= nil then
        return item
    end
    return nil
end

function SunExp_TrySetCollectionItem(collection, index, value)
    if collection == nil then
        return false
    end
    local ok = pcall(function()
        collection:set_Item(index, value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        collection[index] = value
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        collection[index + 1] = value
    end)
    return ok
end
-- </module: core/collections.lua>
end

do
-- <module: combat/negative_buffs.lua>
function SunExp_GetBuffTypeName(buff)
    if buff == nil or buff.buffConfig == nil then
        return nil
    end
    local ok, typeName = pcall(function()
        return buff.buffConfig.Type
    end)
    if ok and typeName ~= nil then
        return tostring(typeName)
    end
    if buff.buffConfig.dataConfig == nil or buff.buffConfig.dataConfig.data == nil then
        return nil
    end
    ok, typeName = pcall(function()
        local data = buff.buffConfig.dataConfig.data
        if data.ContainsKey ~= nil and not data:ContainsKey("Type") then
            return nil
        end
        return data:get_Item("Type")
    end)
    if ok and typeName ~= nil then
        return tostring(typeName)
    end
    return nil
end

SunExp_PositiveBuffExcludeIds = {
    solar_radiance = true,
    gathered_flame = true,
    scorching_canopy = true,
    ember_cloak = true,
    solar_crown = true,
    origin_core_radiance = true,
    cycle_gathered_flame = true,
    afterglow_omen = true
}

function SunExp_NormalizeBuffId(buffId)
    if buffId == nil then
        return nil
    end
    local id = tostring(buffId)
    local prefix = "SunExp_sunexp_"
    if string.sub(id, 1, string.len(prefix)) == prefix then
        return string.sub(id, string.len(prefix) + 1)
    end
    return id
end

function SunExp_IsPositiveBuffExcludedId(buffId)
    local id = SunExp_NormalizeBuffId(buffId)
    return id ~= nil and SunExp_PositiveBuffExcludeIds[id] == true
end

function SunExp_IsPositiveBuffExcludedItem(buff)
    return SunExp_IsPositiveBuffExcludedId(SunExp_GetBuffIdFromItem(buff))
end

function SunExp_IsNegativeBuffItem(buff)
    if SunExp_IsPositiveBuffExcludedItem(buff) then
        return false
    end
    local typeName = SunExp_GetBuffTypeName(buff)
    if typeName == nil then
        return false
    end
    return typeName == "负面" or typeName == "Negative" or string.find(typeName, "负面", 1, true) ~= nil
end

function SunExp_GetBuffIdFromItem(buff)
    if buff == nil or buff.buffConfig == nil then
        return nil
    end
    local ok, buffId = pcall(function()
        return buff.buffConfig.BuffId
    end)
    if ok and buffId ~= nil then
        return buffId
    end
    if buff.buffConfig.dataConfig == nil or buff.buffConfig.dataConfig.data == nil then
        return nil
    end
    ok, buffId = pcall(function()
        local data = buff.buffConfig.dataConfig.data
        if data.ContainsKey ~= nil and not data:ContainsKey("Id") then
            return nil
        end
        return data:get_Item("Id")
    end)
    if ok then
        return buffId
    end
    return nil
end

function SunExp_GetNegativeBuffSummary(target)
    local ids = {}
    local total = 0
    if target == nil then
        return ids, total
    end
    local ok, buffs = pcall(function()
        return target:GetBuffs()
    end)
    if not ok or buffs == nil then
        return ids, total
    end
    local count = SunExp_GetCollectionCount(buffs)
    for i = 0, count - 1 do
        local buff = SunExp_GetCollectionItem(buffs, i)
        if SunExp_IsNegativeBuffItem(buff) then
            local id = SunExp_GetBuffIdFromItem(buff)
            if id ~= nil then
                if buff.buffConfig ~= nil then
                    total = total + (tonumber(buff.buffConfig.Level) or 0)
                end
                table.insert(ids, id)
            end
        end
    end
    return ids, total
end

function SunExp_GetNegativeBuffTotal(target)
    local ids, total = SunExp_GetNegativeBuffSummary(target)
    return tonumber(total) or 0
end

function SunExp_RemoveAllNegativeBuffs(self, target)
    if self == nil then
        return false
    end
    local ids = SunExp_GetNegativeBuffSummary(target)
    for _, id in ipairs(ids) do
        SunExp_RemoveStatusBuff(self, target or self.Self, id)
    end
    return #ids > 0
end

function SunExp_HasNegativeBuff(target)
    if target == nil then
        return false
    end
    local ok, buffs = pcall(function()
        return target:GetBuffs()
    end)
    if not ok or buffs == nil then
        return false
    end
    local count = SunExp_GetCollectionCount(buffs)
    for i = 0, count - 1 do
        if SunExp_IsNegativeBuffItem(SunExp_GetCollectionItem(buffs, i)) then
            return true
        end
    end
    return false
end
-- </module: combat/negative_buffs.lua>
end

do
-- <module: mechanics/radiance_crown_burn.lua>
function SunExp_HasCrownPhase(self, threshold)
    if self == nil or self.Self == nil then
        return false
    end
    local crown = self.Self:GetBuff("SunExp_sunexp_solar_crown")
    return crown ~= nil and SunExp_GetRadianceLevel(self) >= threshold
end

function SunExp_HasSolarCrown(self)
    return self ~= nil and self.Self ~= nil and self.Self:GetBuff("SunExp_sunexp_solar_crown") ~= nil
end

function SunExp_TriggerBurnAll(self, times)
    if self == nil then
        return 0
    end
    local count = tonumber(times) or 1
    if count < 1 then
        count = 1
    end
    local triggered = 0
    for i = 1, count do
        self:SetStatus("All")
        local ok = pcall(function()
            self:RunImmediately("buff_burn", "StartRound")
        end)
        if ok then
            triggered = triggered + 1
        end
    end
    return triggered
end

function SunExp_TriggerSolarCrown(self)
    if not SunExp_HasSolarCrown(self) then
        return false
    end
    local radiance = SunExp_GetRadianceLevel(self)
    if radiance >= 1 then
        local total = SunExp_GetNegativeBuffTotal(self.Self)
        if total > 0 then
            SunExp_RemoveAllNegativeBuffs(self, self.Self)
            self:SetStatus("Self")
            self:AddBuff("buff_burn", tostring(total))
        end
    end
    if radiance >= 4 then
        self:DrawCount("1")
    end
    if radiance >= 8 then
        self:SetStatus("Self")
        self:ChangePower("1")
    end
    if radiance >= 12 then
        local burn = SunExp_GetBuffLevel(self, "buff_burn")
        if burn > 0 then
            self:SetStatus("Self")
            self:RemoveBuff("buff_burn")
            self:AddBuff("SunExp_sunexp_gathered_flame", tostring(burn))
        end
    end
    if radiance >= 15 then
        self:SetStatus("All")
        self:AddBuff("buff_burn", "5")
        SunExp_TriggerBurnAll(self, 1)
    end
    return true
end

function SunExp_IsBurnWardPending(self)
    return SunExp_GetVar(self, "SunExpBurnWardPending", "0") == "1"
end

function SunExp_SetBurnWardPending(self, value)
    SunExp_SetVar(self, "SunExpBurnWardPending", value and "1" or "0")
end

function SunExp_IsSelfBurnProtected(self, includePending)
    if self == nil or self.Self == nil then
        return false
    end
    local ward = self.Self:GetBuff("SunExp_sunexp_ember_cloak")
    if ward ~= nil and ward.buffConfig ~= nil and ward.buffConfig.Level > 0 then
        return true
    end
    if includePending and SunExp_IsBurnWardPending(self) then
        return true
    end
    return false
end

function SunExp_ClearSelfBurnIfProtected(self, includePending)
    if self == nil or self.Self == nil then
        return false
    end
    if SunExp_IsSelfBurnProtected(self, includePending) then
        SunExp_RemoveStatusBuff(self, self.Self, "buff_burn")
        return true
    end
    return false
end

function SunExp_ApplySelfBurn(self, amount, includePending)
    if self == nil or amount == nil or amount <= 0 then
        return false
    end
    if SunExp_IsSelfBurnProtected(self, includePending) then
        if self.Self ~= nil then
            SunExp_RemoveStatusBuff(self, self.Self, "buff_burn")
        end
        return false
    end
    self:SetStatus("Self")
    self:AddBuff("buff_burn", tostring(amount))
    return true
end
-- </module: mechanics/radiance_crown_burn.lua>
end

do
-- <module: mechanics/wuna_role.lua>
function SunExp_WunaEmberBuffId()
    return "SunExp_wuna_wuna_ember"
end

function SunExp_WunaWhiteSunPrayerCardId()
    return "SunExp_wuna_wuna_white_sun_prayer"
end

function SunExp_WunaGraveSongCardId()
    return "SunExp_wuna_wuna_grave_song"
end

function SunExp_WunaCoronationTokenCardId()
    return "SunExp_wuna_wuna_coronation_token"
end

function SunExp_WunaGetSkillTime(key)
    local player = SunExp_PlayerInfo()
    if player == nil or player.SkillTime == nil or key == nil then
        return 0
    end
    local ok, hasKey = pcall(function()
        return player.SkillTime:ContainsKey(key)
    end)
    if not ok then
        return 0
    end
    if not hasKey then
        pcall(function()
            player.SkillTime:set_Item(key, 0)
        end)
        return 0
    end
    local okValue, value = pcall(function()
        return player.SkillTime:get_Item(key)
    end)
    if okValue then
        return tonumber(value) or 0
    end
    return 0
end

function SunExp_WunaSetSkillTime(key, value)
    local player = SunExp_PlayerInfo()
    if player == nil or player.SkillTime == nil or key == nil then
        return false
    end
    local nextValue = math.max(0, math.floor(tonumber(value) or 0))
    local ok = pcall(function()
        player.SkillTime:set_Item(key, nextValue)
    end)
    return ok
end

function SunExp_WunaTickSkillTimes()
    local keys = {
        SunExp_WunaWhiteSunPrayerCardId(),
        SunExp_WunaGraveSongCardId()
    }
    for i = 1, #keys do
        local current = SunExp_WunaGetSkillTime(keys[i])
        if current > 0 then
            SunExp_WunaSetSkillTime(keys[i], current - 1)
        end
    end
end

function SunExp_WunaGetEnemyBurnTotal(self)
    local total = 0
    local targets = SunExp_GetEnemyTargets(self)
    for i = 1, #targets do
        total = total + SunExp_GetStatusBuffLevel(targets[i], "buff_burn")
    end
    return total
end

function SunExp_WunaGetAllBurnTotal(self)
    local total = SunExp_WunaGetEnemyBurnTotal(self)
    if self ~= nil and self.Self ~= nil then
        total = total + SunExp_GetStatusBuffLevel(self.Self, "buff_burn")
    end
    return total
end

function SunExp_WunaClampEmber(self)
    if self == nil or self.Self == nil then
        return 0
    end
    local ember = self.Self:GetBuff(SunExp_WunaEmberBuffId())
    if ember == nil or ember.buffConfig == nil then
        return 0
    end
    local level = math.floor(tonumber(ember.buffConfig.Level) or 0)
    if level > 99 then
        ember.buffConfig.Level = 99
        return 99
    end
    if level <= 0 then
        self:SetStatus("Self")
        self:RemoveBuff(SunExp_WunaEmberBuffId())
        return 0
    end
    return level
end

function SunExp_WunaGetEmberLevel(self)
    if self == nil or self.Self == nil then
        return 0
    end
    return SunExp_GetStatusBuffLevel(self.Self, SunExp_WunaEmberBuffId())
end

function SunExp_WunaAddEmber(self, amount)
    local gain = math.floor(tonumber(amount) or 0)
    if self == nil or gain <= 0 then
        return 0
    end
    self:SetStatus("Self")
    self:AddBuff(SunExp_WunaEmberBuffId(), tostring(gain))
    return SunExp_WunaClampEmber(self)
end

function SunExp_WunaHalveEmber(self)
    if self == nil or self.Self == nil then
        return 0
    end
    local ember = self.Self:GetBuff(SunExp_WunaEmberBuffId())
    if ember == nil or ember.buffConfig == nil then
        return 0
    end
    local nextLevel = math.floor((tonumber(ember.buffConfig.Level) or 0) / 2)
    self:SetStatus("Self")
    if nextLevel <= 0 then
        self:RemoveBuff(SunExp_WunaEmberBuffId())
        return 0
    end
    ember.buffConfig.Level = nextLevel
    return nextLevel
end

function SunExp_WunaTryGainRadianceFromEnemyBurn(self)
    if self == nil or self.Self == nil then
        return false
    end
    local current = SunExp_WunaGetEnemyBurnTotal(self)
    local previous = tonumber(SunExp_GetVar(self, "SunExpWunaPrevEnemyBurn", tostring(current))) or current
    SunExp_SetVar(self, "SunExpWunaPrevEnemyBurn", tostring(current))
    if current <= previous then
        return false
    end
    if SunExp_GetVar(self, "SunExpWunaRadianceDone", "0") == "1" then
        return false
    end
    self:SetStatus("Self")
    self:AddBuff("SunExp_sunexp_solar_radiance", "1")
    SunExp_SetVar(self, "SunExpWunaRadianceDone", "1")
    return true
end

function SunExp_WunaStartRound(self)
    SunExp_WunaTickSkillTimes()
    SunExp_SetVar(self, "SunExpWunaRadianceDone", "0")
    local burnTotal = SunExp_WunaGetAllBurnTotal(self)
    if burnTotal > 0 then
        SunExp_WunaAddEmber(self, burnTotal)
    end
    SunExp_SetVar(self, "SunExpWunaPrevEnemyBurn", tostring(SunExp_WunaGetEnemyBurnTotal(self)))
end

function SunExp_WunaInitCareer(self)
    if self == nil then
        return
    end
    SunExp_WunaSetSkillTime(SunExp_WunaWhiteSunPrayerCardId(), 0)
    SunExp_WunaSetSkillTime(SunExp_WunaGraveSongCardId(), 0)
    SunExp_SetVar(self, "SunExpWunaRadianceDone", "0")
    SunExp_SetVar(self, "SunExpWunaPrevEnemyBurn", "0")
    self:AddEvent("FightStart", function()
        SunExp_SetVar(self, "SunExpWunaRadianceDone", "0")
        SunExp_SetVar(self, "SunExpWunaPrevEnemyBurn", tostring(SunExp_WunaGetEnemyBurnTotal(self)))
    end)
    self:AddEvent("StartRound", function()
        SunExp_WunaStartRound(self)
    end)
    self:AddEvent("EndRound", function()
        SunExp_WunaHalveEmber(self)
    end)
    self:AddEvent("buff_burnOnLevelChange", function()
        SunExp_WunaTryGainRadianceFromEnemyBurn(self)
    end)
end

function SunExp_WunaTryAddCardToHand(self, cardId)
    if self == nil or cardId == nil then
        return false
    end
    local ok = pcall(function()
        self:AddCardById(cardId)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        self:AddCardByData(cardId, "")
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        self:AddCard(cardId)
    end)
    return ok
end

function SunExp_WunaUseWhiteSunPrayer(self)
    local key = SunExp_WunaWhiteSunPrayerCardId()
    local cooldown = SunExp_WunaGetSkillTime(key)
    if cooldown > 0 then
        SunExp_ShowCaption("白曜圣祷尚未冷却。")
        return false
    end
    self:SetStatus("Self")
    SunExp_WunaTryAddCardToHand(self, SunExp_WunaCoronationTokenCardId())
    SunExp_WunaSetSkillTime(key, 5)
    return true
end

function SunExp_WunaIsAlive(self)
    if self == nil or self.Self == nil then
        return false
    end
    local ok, hp = pcall(function()
        return self.Self.CurHp
    end)
    return ok and (tonumber(hp) or 0) > 0
end

function SunExp_WunaHealPercent(self, ratio)
    if self == nil or self.Self == nil then
        return 0
    end
    local ok, maxHp = pcall(function()
        return self.Self.MaxHp
    end)
    if not ok then
        return 0
    end
    local heal = math.max(1, math.floor((tonumber(maxHp) or 0) * (tonumber(ratio) or 0)))
    self:SetStatus("Self")
    self:ChangeHp(tostring(heal))
    return heal
end

function SunExp_WunaUseGraveSong(self)
    local key = SunExp_WunaGraveSongCardId()
    local cooldown = SunExp_WunaGetSkillTime(key)
    if cooldown > 0 then
        SunExp_ShowCaption("圣庭墓曲尚未冷却。")
        return false
    end
    local ember = SunExp_WunaGetEmberLevel(self)
    if ember <= 30 then
        SunExp_ShowCaption("余烬不足。")
        return false
    end
    local flame = SunExp_GetBuffLevel(self, "SunExp_sunexp_gathered_flame")
    self:SetStatus("Self")
    self:RemoveBuff(SunExp_WunaEmberBuffId())
    self:RemoveBuff("SunExp_sunexp_ember_cloak")
    if flame > 0 then
        self:AddBuff("buff_burn", tostring(flame))
        self:RunImmediately("buff_burn", "StartRound")
    end
    SunExp_WunaSetSkillTime(key, 4)
    if not SunExp_WunaIsAlive(self) then
        return true
    end
    SunExp_WunaHealPercent(self, 0.3)
    self:SetStatus("Self")
    self:AddBuff("SunExp_sunexp_ember_cloak", "1")
    if flame > 0 then
        self:SetStatus("All")
        self:AddBuff("buff_burn", tostring(flame))
        self:RunImmediately("buff_burn", "StartRound")
    end
    return true
end

function SunExp_ApplyWunaEmberDamageBonus(self, amount)
    local base = math.floor(tonumber(amount) or 0)
    if base <= 0 then
        return base
    end
    local ember = SunExp_WunaGetEmberLevel(self)
    if ember <= 0 then
        return base
    end
    return math.floor(base * (100 + ember) / 100)
end
-- </module: mechanics/wuna_role.lua>
end

do
-- <module: mechanics/hooks.lua>
function SunExp_RegisterHook(self, hookKey, tokenKey)
    if self == nil or self.Vars == nil then
        return "0"
    end
    if self.Vars:ContainsKey(hookKey) and self.Vars:get_Item(hookKey) == "1" then
        return nil
    end
    local token = tonumber(SunExp_GetVar(self, tokenKey, "0")) or 0
    token = token + 1
    self.Vars:set_Item(hookKey, "1")
    self.Vars:set_Item(tokenKey, tostring(token))
    return tostring(token)
end

function SunExp_IsHookTokenActive(self, tokenKey, token)
    if self == nil or self.Vars == nil then
        return true
    end
    return SunExp_GetVar(self, tokenKey, "") == tostring(token)
end

function SunExp_ClearHook(self, hookKey, tokenKey)
    if self == nil or self.Vars == nil then
        return
    end
    self.Vars:set_Item(hookKey, "0")
    local token = tonumber(SunExp_GetVar(self, tokenKey, "0")) or 0
    self.Vars:set_Item(tokenKey, tostring(token + 1))
end
-- </module: mechanics/hooks.lua>
end

do
-- <module: mechanics/solar_keyword_field.lua>
SunExpSolarKeyword = "SunExpSolar"
SunExpBodyBurnBuffId = "SunExp_sunexp_body_burn"
SunExpBurnUpperBound = 49

function SunExp_FieldStateKey(name)
    return "SunExpField_" .. tostring(name)
end

function SunExp_FieldBuffId(fieldId)
    if fieldId == "scorching_canopy" then
        return "SunExp_sunexp_scorching_canopy"
    end
    return nil
end

function SunExp_GetActiveFieldId(self)
    return SunExp_GetVar(self, "SunExpActiveFieldId", "")
end

function SunExp_GetActiveFieldEpoch(self)
    return tonumber(SunExp_GetVar(self, "SunExpActiveFieldEpoch", "0")) or 0
end

function SunExp_SetActiveField(self, fieldId)
    local current = SunExp_GetActiveFieldId(self)
    if current == fieldId then
        return SunExp_GetActiveFieldEpoch(self)
    end
    local epoch = SunExp_GetActiveFieldEpoch(self) + 1
    SunExp_SetVar(self, "SunExpActiveFieldId", fieldId or "")
    SunExp_SetVar(self, "SunExpActiveFieldEpoch", epoch)
    SunExp_SetVar(self, "SunExpActiveFieldStacks", "0")
    return epoch
end

function SunExp_IsActiveField(self, fieldId, epoch, token)
    if self == nil or fieldId == nil then
        return false
    end
    if SunExp_GetActiveFieldId(self) ~= fieldId then
        return false
    end
    if epoch ~= nil and SunExp_GetActiveFieldEpoch(self) ~= tonumber(epoch) then
        return false
    end
    if token ~= nil and not SunExp_IsHookTokenActive(self, SunExp_FieldStateKey(fieldId) .. "Token", token) then
        return false
    end
    return true
end

function SunExp_SyncFieldStacks(self, fieldId)
    local buffId = SunExp_FieldBuffId(fieldId)
    if self == nil or self.Self == nil or buffId == nil then
        return 0
    end
    local level = SunExp_GetBuffLevel(self, buffId)
    if SunExp_GetActiveFieldId(self) == fieldId then
        SunExp_SetVar(self, "SunExpActiveFieldStacks", level)
    end
    return level
end

function SunExp_InternalClearFieldBuff(self, fieldId)
    local buffId = SunExp_FieldBuffId(fieldId)
    if self == nil or buffId == nil then
        return false
    end
    SunExp_SetVar(self, "SunExpFieldInternalClear", "1")
    self:SetStatus("Self")
    local ok = pcall(function()
        self:RemoveBuff(buffId)
    end)
    SunExp_SetVar(self, "SunExpFieldInternalClear", "0")
    return ok
end

function SunExp_ApplyFieldBuff(self, fieldId, amount)
    local count = math.floor(tonumber(amount) or 0)
    local buffId = SunExp_FieldBuffId(fieldId)
    if self == nil or buffId == nil or count <= 0 then
        return false
    end
    local active = SunExp_GetActiveFieldId(self)
    if active ~= "" and active ~= fieldId then
        SunExp_InternalClearFieldBuff(self, active)
    end
    SunExp_SetActiveField(self, fieldId)
    self:SetStatus("Self")
    self:AddBuff(buffId, tostring(count))
    SunExp_SyncFieldStacks(self, fieldId)
    return true
end

function SunExp_OnFieldBuffApplied(self, fieldId)
    if self == nil or fieldId == nil then
        return
    end
    if SunExp_GetActiveFieldId(self) == "" then
        SunExp_SetActiveField(self, fieldId)
    end
    local hookKey = SunExp_FieldStateKey(fieldId) .. "Hook"
    local tokenKey = SunExp_FieldStateKey(fieldId) .. "Token"
    local token = SunExp_RegisterHook(self, hookKey, tokenKey)
    SunExp_SyncFieldStacks(self, fieldId)
    if token == nil then
        return
    end
    local epoch = SunExp_GetActiveFieldEpoch(self)
    self:AddEvent("StartRound", function()
        if not SunExp_IsActiveField(self, fieldId, epoch, token) then
            return
        end
        SunExp_FieldStartRound(self, fieldId)
    end)
end

function SunExp_OnFieldBuffCleared(self, fieldId)
    if self == nil or fieldId == nil then
        return
    end
    local hookKey = SunExp_FieldStateKey(fieldId) .. "Hook"
    local tokenKey = SunExp_FieldStateKey(fieldId) .. "Token"
    local externalClear = SunExp_GetVar(self, "SunExpFieldInternalClear", "0") ~= "1"
    local wasActive = SunExp_GetActiveFieldId(self) == fieldId
    local stacks = tonumber(SunExp_GetVar(self, "SunExpActiveFieldStacks", "1")) or 1
    SunExp_ClearHook(self, hookKey, tokenKey)
    if not externalClear or not wasActive or stacks <= 0 then
        return
    end
    local buffId = SunExp_FieldBuffId(fieldId)
    if buffId == nil then
        return
    end
    self:SetStatus("Self")
    self:AddBuff(buffId, tostring(stacks))
end

function SunExp_FieldStartRound(self, fieldId)
    if fieldId ~= "scorching_canopy" then
        return false
    end
    local count = SunExp_SyncFieldStacks(self, fieldId)
    if count <= 0 then
        return false
    end
    self:SetStatus("All")
    self:AddBuff("buff_burn", tostring(count))
    SunExp_ClearSelfBurnIfProtected(self, true)
    return true
end

function SunExp_HandleSolarCardUsed(self, cost)
    if self == nil then
        return false
    end
    if SunExp_HasSolarCrown(self) then
        return SunExp_TriggerSolarCrown(self)
    end
    local gain = math.floor(tonumber(cost) or 0)
    if gain <= 0 then
        return false
    end
    self:SetStatus("Self")
    self:AddBuff("SunExp_sunexp_solar_radiance", tostring(gain))
    return true
end

function SunExp_GetDataValue(data, key)
    if data == nil or key == nil then
        return nil
    end
    local ok, value = pcall(function()
        if data.ContainsKey ~= nil and not data:ContainsKey(key) then
            return nil
        end
        return data:get_Item(key)
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return data[key]
    end)
    if ok then
        return value
    end
    return nil
end

function SunExp_GetCardVar(card, key, defaultValue)
    if card == nil or key == nil then
        return defaultValue
    end
    local vars = card.Vars
    if vars == nil and card.dataConfig ~= nil then
        vars = card.dataConfig.Vars
    end
    if vars == nil then
        return defaultValue
    end
    local ok, value = pcall(function()
        if vars.ContainsKey ~= nil and not vars:ContainsKey(key) then
            return nil
        end
        return vars:get_Item(key)
    end)
    if ok and value ~= nil then
        return value
    end
    ok, value = pcall(function()
        return vars[key]
    end)
    if ok and value ~= nil then
        return value
    end
    return defaultValue
end

function SunExp_GetEnchCardCost(self)
    if self == nil then
        return 0
    end
    local ok, card = pcall(function()
        return self:EnchGetCard()
    end)
    if not ok or card == nil then
        ok, card = pcall(function()
            return EnchGetCard()
        end)
    end
    if not ok or card == nil then
        return 0
    end
    local data = card.data
    if data == nil and card.dataConfig ~= nil then
        data = card.dataConfig.data
    end
    local base = tonumber(SunExp_GetDataValue(data, "Expend")) or 0
    local exCost = tonumber(SunExp_GetCardVar(card, "ExCost", "0")) or 0
    local onceExCost = tonumber(SunExp_GetCardVar(card, "OnceExCost", "0")) or 0
    local totalExCost = tonumber(SunExp_GetCardVar(card, "TotalExCost", "0")) or 0
    local total = base + exCost + onceExCost + totalExCost
    if total < 0 then
        total = 0
    end
    return math.floor(total)
end

function SunExp_HandleSolarEnchCardUsed(self)
    return SunExp_HandleSolarCardUsed(self, SunExp_GetEnchCardCost(self))
end

function SunExp_CalcSolarKeywordBonusDamage(self, target, coefficientScale)
    local scale = tonumber(coefficientScale) or 1
    return math.floor(SunExp_CalcSolarCoefficient(self, target) * scale)
end

function SunExp_DealSolarKeywordBonusDamage(self, target, fallbackStatus, coefficientScale)
    local damage = SunExp_CalcSolarKeywordBonusDamage(self, target, coefficientScale)
    if damage <= 0 then
        return false
    end
    if target ~= nil then
        SunExp_SetStatusForBuff(self, target, fallbackStatus or "Target")
    elseif fallbackStatus ~= nil then
        self:SetStatus(fallbackStatus)
    end
    return SunExp_DealDamage(self, damage)
end

function SunExp_BodyBurnDamagePerStack(target)
    if target == nil then
        return 1
    end
    local ok, maxHp = pcall(function()
        return target.MaxHp
    end)
    if not ok or maxHp == nil then
        maxHp = 0
    end
    return math.floor((tonumber(maxHp) or 0) * 0.005) + 1
end

function SunExp_TriggerBodyBurn(self)
    local level = SunExp_GetBuffLevel(self, SunExpBodyBurnBuffId)
    if level <= 0 then
        return false
    end
    local damage = SunExp_BodyBurnDamagePerStack(self.Self) * level
    self:SetStatus("Self")
    if damage > 0 then
        self:Damage(tostring(damage), "True")
    end
    self:RemoveBuff(SunExpBodyBurnBuffId)
    return true
end

function SunExp_AddBodyBurn(self, target, amount)
    local count = math.floor(tonumber(amount) or 0)
    if count <= 0 then
        return false
    end
    return SunExp_AddStatusBuff(self, target, SunExpBodyBurnBuffId, tostring(count), "Target")
end

function SunExp_HandleBurnOverflow(self, target, amount)
    if self == nil or target == nil or not SunExp_IsActiveField(self, "scorching_canopy") then
        return false
    end
    if SunExp_IsSelfStatus(self, target) and SunExp_IsSelfBurnProtected(self, true) then
        return false
    end
    local add = math.floor(tonumber(amount) or 0)
    if add <= 0 then
        return false
    end
    local current = SunExp_GetStatusBuffLevel(target, "buff_burn")
    local overflow = current + add - SunExpBurnUpperBound
    if overflow <= 0 then
        return false
    end
    return SunExp_AddBodyBurn(self, target, overflow)
end

function SunExp_GetHookArg(args, index)
    if args == nil then
        return nil
    end
    local value = SunExp_GetCollectionItem(args, index - 1)
    if value ~= nil then
        return value
    end
    local ok
    ok, value = pcall(function()
        return args[index]
    end)
    if ok then
        return value
    end
    return nil
end

function SunExp_NormalizeHookBuffId(value)
    if value == nil then
        return nil
    end
    local text = tostring(value)
    local prefix = "DataId."
    if string.sub(text, 1, string.len(prefix)) == prefix then
        text = string.sub(text, string.len(prefix) + 1)
    end
    return text
end

function SunExp_GetHookExecutor(context)
    local target = SunExp_TryGetHookTarget(context)
    if target ~= nil and target.Self ~= nil then
        return target
    end
    if context ~= nil and context.Self ~= nil then
        return context
    end
    return nil
end

function SunExp_GetHookTargets(executor)
    local targets = {}
    if executor == nil then
        return targets
    end
    local seen = {}
    local function addTarget(target)
        if target == nil then
            return
        end
        local key = target
        if target.InstanceId ~= nil then
            key = tostring(target.InstanceId)
        end
        if seen[key] then
            return
        end
        seen[key] = true
        table.insert(targets, target)
    end
    local object = executor.Object
    local count = SunExp_GetCollectionCount(object)
    for i = 0, count - 1 do
        addTarget(SunExp_GetCollectionItem(object, i))
    end
    if #targets == 0 then
        addTarget(executor.Target)
    end
    if #targets == 0 then
        addTarget(executor.Self)
    end
    return targets
end

function SunExp_OnScriptExecutorAddBuffBefore(...)
    local contexts = {...}
    local handled = {}
    for i = 1, #contexts do
        local context = contexts[i]
        local executor = SunExp_GetHookExecutor(context)
        if executor ~= nil then
            local args = SunExp_TryGetHookArguments(context)
            local buffId = SunExp_NormalizeHookBuffId(SunExp_GetHookArg(args, 1))
            if buffId == "buff_burn" then
                local amount = tonumber(SunExp_GetHookArg(args, 2)) or 0
                local targets = SunExp_GetHookTargets(executor)
                for j = 1, #targets do
                    local target = targets[j]
                    local key = target
                    if target ~= nil and target.InstanceId ~= nil then
                        key = tostring(target.InstanceId)
                    end
                    if key ~= nil and not handled[key] then
                        handled[key] = true
                        SunExp_HandleBurnOverflow(executor, target, amount)
                    end
                end
            end
        end
    end
end
-- </module: mechanics/solar_keyword_field.lua>
end

do
-- <module: cards/flamewheel.lua>
function SunExp_FlamewheelKey()
    return "SunExp_flamewheel_recurrence_count"
end

function SunExp_GetFlamewheelSkillTime()
    local skillTime = nil
    pcall(function()
        if CS ~= nil and CS.ScriptExecutor ~= nil and CS.ScriptExecutor.PlayerInfo ~= nil then
            skillTime = CS.ScriptExecutor.PlayerInfo.SkillTime
        end
    end)
    return skillTime
end

function SunExp_GetFlamewheelUsed()
    local st = SunExp_GetFlamewheelSkillTime()
    if st == nil then
        return 0
    end
    local key = SunExp_FlamewheelKey()
    pcall(function()
        if st.ContainsKey ~= nil and not st:ContainsKey(key) then
            st:set_Item(key, 0)
        end
    end)
    local ok, value = pcall(function()
        return st:get_Item(key)
    end)
    if ok then
        return tonumber(value) or 0
    end
    return 0
end

function SunExp_SetFlamewheelUsed(value)
    local st = SunExp_GetFlamewheelSkillTime()
    if st == nil then
        return false
    end
    local ok = pcall(function()
        st:set_Item(SunExp_FlamewheelKey(), tonumber(value) or 0)
    end)
    return ok
end

function SunExp_SetFlamewheelCost(cardData, used)
    if cardData == nil then
        return false
    end
    local vars = nil
    pcall(function()
        vars = cardData.Vars
    end)
    if vars == nil then
        return false
    end
    local value = tostring(used or SunExp_GetFlamewheelUsed())
    local ok = pcall(function()
        vars:set_Item("ExCost", value)
    end)
    if ok then
        return true
    end
    ok = pcall(function()
        vars["ExCost"] = value
    end)
    return ok
end

function SunExp_UpdateFlamewheelCost(cardData)
    return SunExp_SetFlamewheelCost(cardData)
end

function SunExp_IsFlamewheelCardItem(item)
    if item == nil then
        return false
    end
    local id = nil
    if item.data ~= nil and item.data.ContainsKey ~= nil and item.data:ContainsKey("Id") then
        id = item.data:get_Item("Id")
    end
    if id == nil and item.dataConfig ~= nil and item.dataConfig.data ~= nil and item.dataConfig.data.ContainsKey ~= nil and item.dataConfig.data:ContainsKey("Id") then
        id = item.dataConfig.data:get_Item("Id")
    end
    if id == nil then
        return false
    end
    return string.find(tostring(id), "flamewheel_recurrence", 1, true) ~= nil
end

function SunExp_TrySetFlamewheelItemCost(item, used)
    if item == nil then
        return false
    end
    local value = tostring(used)
    local changed = false
    pcall(function()
        if item.Vars ~= nil then
            item.Vars:set_Item("ExCost", value)
            changed = true
        end
    end)
    pcall(function()
        if item.dataConfig ~= nil and item.dataConfig.Vars ~= nil then
            item.dataConfig.Vars:set_Item("ExCost", value)
            changed = true
        end
    end)
    if changed then
        pcall(function()
            if item.DataUpdate ~= nil then
                item:DataUpdate()
            end
        end)
    end
    return changed
end

function SunExp_RefreshFlamewheelHand(self, used)
    if self == nil then
        return false
    end
    if SunExp_GetVar(self, "SunExpFlamewheelRefreshBusy", "0") == "1" then
        return false
    end
    SunExp_SetVar(self, "SunExpFlamewheelRefreshBusy", "1")
    local changed = false
    pcall(function()
        local hand = nil
        pcall(function()
            hand = self.HandCard
        end)
        if hand == nil then
            return
        end
        local nextCost = used
        if nextCost == nil then
            nextCost = SunExp_GetFlamewheelUsed()
        end
        local count = SunExp_GetCollectionCount(hand)
        for i = 0, count - 1 do
            local item = SunExp_GetCollectionItem(hand, i)
            if SunExp_IsFlamewheelCardItem(item) and SunExp_TrySetFlamewheelItemCost(item, nextCost) then
                changed = true
            end
        end
    end)
    SunExp_SetVar(self, "SunExpFlamewheelRefreshBusy", "0")
    return changed
end

function SunExp_RefreshFlamewheelCosts(self, used)
    return SunExp_RefreshFlamewheelHand(self, used)
end
-- </module: cards/flamewheel.lua>
end

do
-- <module: registry.lua>
function SunExp_RegisterDynamicMethod(config, name, fn)
    if config == nil or fn == nil then
        return
    end
    config:AddDynamicMethod(name, fn)
end

function SunExp_RegisterDynamicMethods(config)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerInfo", SunExp_PlayerInfo)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerGetVar", SunExp_PlayerGetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_PlayerSetVar", SunExp_PlayerSetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GainGold", SunExp_GainGold)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddCardReward", SunExp_AddCardReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddRelicReward", SunExp_AddRelicReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBlessReward", SunExp_AddBlessReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_EndEvent", SunExp_EndEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_ShowCaption", SunExp_ShowCaption)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaProgressKey", SunExp_WunaProgressKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetWunaProgress", SunExp_GetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetWunaProgress", SunExp_SetWunaProgress)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaLevelKey", SunExp_WunaLevelKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapLevel", SunExp_GetCurrentMapLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapLevelNumber", SunExp_GetCurrentMapLevelNumber)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasWunaEventInCurrentLevel", SunExp_HasWunaEventInCurrentLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_MarkWunaEventInCurrentLevel", SunExp_MarkWunaEventInCurrentLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_AdvanceWunaEvent", SunExp_AdvanceWunaEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaFinish", SunExp_WunaFinish)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetEventChoiceVar", SunExp_TrySetEventChoiceVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetEventChoices", SunExp_SetEventChoices)
    SunExp_RegisterDynamicMethod(config, "SunExp_BeginWunaRepeatEvent", SunExp_BeginWunaRepeatEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_BeginWunaEvent", SunExp_BeginWunaEvent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardCard", SunExp_WunaRewardCard)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardRelic", SunExp_WunaRewardRelic)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardBless", SunExp_WunaRewardBless)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRewardNone", SunExp_WunaRewardNone)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaRepeatReward", SunExp_WunaRepeatReward)
    SunExp_RegisterDynamicMethod(config, "SunExp_SolarEventMapId", SunExp_SolarEventMapId)
    SunExp_RegisterDynamicMethod(config, "SunExp_SolarEventPlaceholderNodeId", SunExp_SolarEventPlaceholderNodeId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventMapId", SunExp_IsSolarEventMapId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventPlaceholderNodeId", SunExp_IsSolarEventPlaceholderNodeId)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentSolarEventId", SunExp_GetCurrentSolarEventId)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookField", SunExp_TryGetHookField)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookArguments", SunExp_TryGetHookArguments)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetHookTarget", SunExp_TryGetHookTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetNodeData", SunExp_TrySetNodeData)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryGetNodeDataValue", SunExp_TryGetNodeDataValue)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSolarEventNode", SunExp_IsSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsEventNode", SunExp_IsEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetMapTree", SunExp_GetMapTree)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCurrentMapTree", SunExp_GetCurrentMapTree)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerSegmentSize", SunExp_GetSolarLayerSegmentSize)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerStartIndex", SunExp_GetSolarLayerStartIndex)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarLayerRange", SunExp_GetSolarLayerRange)
    SunExp_RegisterDynamicMethod(config, "SunExp_CreateSolarEventNode", SunExp_CreateSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSelectNodes", SunExp_GetSelectNodes)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsBreakNode", SunExp_IsBreakNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsProtectedFixedEventNode", SunExp_IsProtectedFixedEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetSolarEventNode", SunExp_TrySetSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryReplaceNodeAt", SunExp_TryReplaceNodeAt)
    SunExp_RegisterDynamicMethod(config, "SunExp_EnsureSolarEventInCurrentLayer", SunExp_EnsureSolarEventInCurrentLayer)
    SunExp_RegisterDynamicMethod(config, "SunExp_EnsureSolarEventInCurrentLayerFromHook", SunExp_EnsureSolarEventInCurrentLayerFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventNode", SunExp_TryAppendSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventNodeFromHook", SunExp_TryAppendSolarEventNodeFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventNode", SunExp_TryRepairSolarEventNode)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventNodes", SunExp_TryRepairSolarEventNodes)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventSyncedMapData", SunExp_TryRepairSolarEventSyncedMapData)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventSelectedNodesFromHook", SunExp_TryRepairSolarEventSelectedNodesFromHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetMapSelectSolarChoiceCounts", SunExp_GetMapSelectSolarChoiceCounts)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryCreateSolarEventChoiceUI", SunExp_TryCreateSolarEventChoiceUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventChoiceForUI", SunExp_TryAppendSolarEventChoiceForUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryAppendSolarEventChoiceUI", SunExp_TryAppendSolarEventChoiceUI)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventMapArrays", SunExp_TryRepairSolarEventMapArrays)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventMapSelection", SunExp_TryRepairSolarEventMapSelection)
    SunExp_RegisterDynamicMethod(config, "SunExp_TryRepairSolarEventGeneratedMap", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetVar", SunExp_GetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetVar", SunExp_SetVar)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffLevel", SunExp_GetBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRadianceLevel", SunExp_GetRadianceLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetSolarMultiplier", SunExp_GetSolarMultiplier)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarCoefficient", SunExp_CalcSolarCoefficient)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealDamage", SunExp_DealDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddDamageDescription", SunExp_AddDamageDescription)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarKeywordDamage", SunExp_CalcSolarKeywordDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarKeywordBlock", SunExp_CalcSolarKeywordBlock)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealSolarKeywordDamage", SunExp_DealSolarKeywordDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealSolarKeywordDamageAllEnemies", SunExp_DealSolarKeywordDamageAllEnemies)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplySolarKeywordSkill", SunExp_ApplySolarKeywordSkill)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSparkDamage", SunExp_CalcSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlareCutDamage", SunExp_CalcFlareCutDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlareCutBonusDamage", SunExp_CalcFlareCutBonusDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarSparkBaseDamage", SunExp_CalcSolarSparkBaseDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarSparkDamage", SunExp_CalcSolarSparkDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarSparkBonusDamage", SunExp_CalcSolarSparkBonusDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownPressureDamage", SunExp_CalcCrownPressureDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcCrownCoreFlashDamage", SunExp_CalcCrownCoreFlashDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcFlamePierceDamage", SunExp_CalcFlamePierceDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSmokeErosionDamage", SunExp_CalcSmokeErosionDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetEnemyTargets", SunExp_GetEnemyTargets)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfStatus", SunExp_IsSelfStatus)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetPrimaryTarget", SunExp_GetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetPrimaryTarget", SunExp_SetPrimaryTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusForBuff", SunExp_SetStatusForBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuff", SunExp_GetStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetStatusBuffLevel", SunExp_GetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveStatusBuff", SunExp_RemoveStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetStatusBuffLevel", SunExp_SetStatusBuffLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddStatusBuff", SunExp_AddStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerStatusBuff", SunExp_TriggerStatusBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurn", SunExp_TriggerBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurnAllEnemies", SunExp_TriggerBurnAllEnemies)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetRandomEnemyTarget", SunExp_GetRandomEnemyTarget)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBurnToRandomEnemy", SunExp_AddBurnToRandomEnemy)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveBuffStacks", SunExp_RemoveBuffStacks)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionCount", SunExp_GetCollectionCount)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetCollectionItem", SunExp_GetCollectionItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetCollectionItem", SunExp_TrySetCollectionItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffTypeName", SunExp_GetBuffTypeName)
    SunExp_RegisterDynamicMethod(config, "SunExp_NormalizeBuffId", SunExp_NormalizeBuffId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedId", SunExp_IsPositiveBuffExcludedId)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsPositiveBuffExcludedItem", SunExp_IsPositiveBuffExcludedItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsNegativeBuffItem", SunExp_IsNegativeBuffItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetBuffIdFromItem", SunExp_GetBuffIdFromItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffSummary", SunExp_GetNegativeBuffSummary)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetNegativeBuffTotal", SunExp_GetNegativeBuffTotal)
    SunExp_RegisterDynamicMethod(config, "SunExp_RemoveAllNegativeBuffs", SunExp_RemoveAllNegativeBuffs)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasNegativeBuff", SunExp_HasNegativeBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasCrownPhase", SunExp_HasCrownPhase)
    SunExp_RegisterDynamicMethod(config, "SunExp_HasSolarCrown", SunExp_HasSolarCrown)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBurnAll", SunExp_TriggerBurnAll)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerSolarCrown", SunExp_TriggerSolarCrown)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsBurnWardPending", SunExp_IsBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetBurnWardPending", SunExp_SetBurnWardPending)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsSelfBurnProtected", SunExp_IsSelfBurnProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearSelfBurnIfProtected", SunExp_ClearSelfBurnIfProtected)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplySelfBurn", SunExp_ApplySelfBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaEmberBuffId", SunExp_WunaEmberBuffId)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaWhiteSunPrayerCardId", SunExp_WunaWhiteSunPrayerCardId)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaGraveSongCardId", SunExp_WunaGraveSongCardId)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaCoronationTokenCardId", SunExp_WunaCoronationTokenCardId)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaGetSkillTime", SunExp_WunaGetSkillTime)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaSetSkillTime", SunExp_WunaSetSkillTime)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaTickSkillTimes", SunExp_WunaTickSkillTimes)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaGetEnemyBurnTotal", SunExp_WunaGetEnemyBurnTotal)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaGetAllBurnTotal", SunExp_WunaGetAllBurnTotal)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaClampEmber", SunExp_WunaClampEmber)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaGetEmberLevel", SunExp_WunaGetEmberLevel)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaAddEmber", SunExp_WunaAddEmber)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaHalveEmber", SunExp_WunaHalveEmber)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaTryGainRadianceFromEnemyBurn", SunExp_WunaTryGainRadianceFromEnemyBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaStartRound", SunExp_WunaStartRound)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaInitCareer", SunExp_WunaInitCareer)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaTryAddCardToHand", SunExp_WunaTryAddCardToHand)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaUseWhiteSunPrayer", SunExp_WunaUseWhiteSunPrayer)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaIsAlive", SunExp_WunaIsAlive)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaHealPercent", SunExp_WunaHealPercent)
    SunExp_RegisterDynamicMethod(config, "SunExp_WunaUseGraveSong", SunExp_WunaUseGraveSong)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplyWunaEmberDamageBonus", SunExp_ApplyWunaEmberDamageBonus)
    SunExp_RegisterDynamicMethod(config, "SunExp_RegisterHook", SunExp_RegisterHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsHookTokenActive", SunExp_IsHookTokenActive)
    SunExp_RegisterDynamicMethod(config, "SunExp_ClearHook", SunExp_ClearHook)
    SunExp_RegisterDynamicMethod(config, "SunExp_ApplyFieldBuff", SunExp_ApplyFieldBuff)
    SunExp_RegisterDynamicMethod(config, "SunExp_OnFieldBuffApplied", SunExp_OnFieldBuffApplied)
    SunExp_RegisterDynamicMethod(config, "SunExp_OnFieldBuffCleared", SunExp_OnFieldBuffCleared)
    SunExp_RegisterDynamicMethod(config, "SunExp_FieldStartRound", SunExp_FieldStartRound)
    SunExp_RegisterDynamicMethod(config, "SunExp_HandleSolarCardUsed", SunExp_HandleSolarCardUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetEnchCardCost", SunExp_GetEnchCardCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_HandleSolarEnchCardUsed", SunExp_HandleSolarEnchCardUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_CalcSolarKeywordBonusDamage", SunExp_CalcSolarKeywordBonusDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_DealSolarKeywordBonusDamage", SunExp_DealSolarKeywordBonusDamage)
    SunExp_RegisterDynamicMethod(config, "SunExp_TriggerBodyBurn", SunExp_TriggerBodyBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_AddBodyBurn", SunExp_AddBodyBurn)
    SunExp_RegisterDynamicMethod(config, "SunExp_HandleBurnOverflow", SunExp_HandleBurnOverflow)
    SunExp_RegisterDynamicMethod(config, "SunExp_OnScriptExecutorAddBuffBefore", SunExp_OnScriptExecutorAddBuffBefore)
    SunExp_RegisterDynamicMethod(config, "SunExp_FlamewheelKey", SunExp_FlamewheelKey)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetFlamewheelSkillTime", SunExp_GetFlamewheelSkillTime)
    SunExp_RegisterDynamicMethod(config, "SunExp_GetFlamewheelUsed", SunExp_GetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetFlamewheelUsed", SunExp_SetFlamewheelUsed)
    SunExp_RegisterDynamicMethod(config, "SunExp_SetFlamewheelCost", SunExp_SetFlamewheelCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_UpdateFlamewheelCost", SunExp_UpdateFlamewheelCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_IsFlamewheelCardItem", SunExp_IsFlamewheelCardItem)
    SunExp_RegisterDynamicMethod(config, "SunExp_TrySetFlamewheelItemCost", SunExp_TrySetFlamewheelItemCost)
    SunExp_RegisterDynamicMethod(config, "SunExp_RefreshFlamewheelHand", SunExp_RefreshFlamewheelHand)
    SunExp_RegisterDynamicMethod(config, "SunExp_RefreshFlamewheelCosts", SunExp_RefreshFlamewheelCosts)
end
-- </module: registry.lua>
end

do
-- <module: setup.lua>
function SunExp_TryAddMethodHookBefore(config, typeDotMethod, fn)
    if config == nil or typeDotMethod == nil or fn == nil then
        return false
    end
    local ok = pcall(function()
        config:AddMethodHookBefore(typeDotMethod, fn)
    end)
    return ok
end

function SunExp_TryAddMethodHookAfter(config, typeDotMethod, fn)
    if config == nil or typeDotMethod == nil or fn == nil then
        return false
    end
    local ok = pcall(function()
        config:AddMethodHookAfter(typeDotMethod, fn)
    end)
    return ok
end

function ModConfig:Setup()
    SunExp_RegisterDynamicMethods(self)
    SunExp_TryAddMethodHookBefore(self, "MapSelectUI.ReadyToSelect", SunExp_EnsureSolarEventInCurrentLayerFromHook)
    SunExp_TryAddMethodHookAfter(self, "NormalMapManager.RandomGenerate", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_TryAddMethodHookAfter(self, "NormalMapManager.GeneratrMap", SunExp_TryRepairSolarEventGeneratedMap)
    SunExp_TryAddMethodHookBefore(self, "MapManager.UserCode_CmdSelectMap__String[]__String[]__NetworkConnectionToClient", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.UserCode_CmdSelectMapIncludeSender__String[]__String[]__NetworkConnectionToClient", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.CmdSelectMap", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.CmdSelectMapIncludeSender", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.TargetUpdateMap", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "MapManager.RpcUpdateMap", SunExp_TryRepairSolarEventMapSelection)
    SunExp_TryAddMethodHookBefore(self, "ScriptExecutor.AddBuff", SunExp_OnScriptExecutorAddBuffBefore)
end
-- </module: setup.lua>
end
