-- Generated by tools/Build-SunExpEntry.ps1 from SunExp/Scripts/_src.
-- Edit the _src modules, then rebuild this file.
-- The game runtime only guarantees Scripts/Entry.lua as the mod load entry.

do
-- <module: setup.lua>
function ModConfig:Setup()
    if CS ~= nil and CS.UnityEngine ~= nil and CS.UnityEngine.Debug ~= nil then
        CS.UnityEngine.Debug.Log("[SunExp] Lua Entry.lua compatibility setup loaded; runtime logic is in Entry.dll.")
    end
end
-- </module: setup.lua>
end
